PROGRAM TEST_NN_SCATTERING_VARIATIONAL_ENERGIES_CHANNELS
  USE SCATTERING_NN_VARIATIONAL
  USE QUANTUM_NUMBERS
  USE OPERATING_SYSTEM_LINUX
  USE NUMBER_DIFFERENCES
  USE EFT_PLESS
  IMPLICIT NONE 
  INTEGER, PARAMETER :: NE = 200
  DOUBLE PRECISION, PARAMETER :: EMAX = 1.D0
  INTEGER, PARAMETER :: LMAX = 2
  INTEGER, PARAMETER :: JMAX = 2
  INTEGER, PARAMETER :: TZ = 0
  INTEGER, PARAMETER :: LEMP = 0
  CHARACTER(LEN=*), PARAMETER :: OUT_DIR_AV18 = 'output/test_AV18_2/'
  CHARACTER(LEN=*), PARAMETER :: OUT_DIR_EFT_15 = 'output/test_EFT_pless_15_2/'
  CHARACTER(LEN=*), PARAMETER :: OUT_DIR_EFT_15_DYNAMIC = 'output/test_EFT_pless_15_dynamic_2/'

  TYPE(SCATTERING_CHANNEL), ALLOCATABLE :: CHANNELS(:)
  CHARACTER(LEN=16) :: CHANNEL_NAME
  DOUBLE PRECISION :: ENERGIES(NE)
  TYPE(PHASE_SHIFT_RESULT), ALLOCATABLE :: PHASE_SHIFTS(:,:)
  INTEGER :: NCHANNELS, ICH, IE, I
  TYPE(LECS_EFT_PLESS) :: LECS_15

  CALL PREPARE_CHANNELS(LMAX, JMAX, TZ, CHANNELS)
  NCHANNELS = SIZE(CHANNELS)
  ALLOCATE(PHASE_SHIFTS(NCHANNELS, NE))
  
  ENERGIES = [(EMAX * I / NE, I = 1, NE)]

  CALL NN_SCATTERING_VARIATIONAL_ENERGIES_CHANNELS(ENERGIES, CHANNELS, LEMP, PHASE_SHIFTS, IPOT = 18, ILB = 1)

  ! Output results to files
  ! Create output directory if it doesn't exist
  CALL CREATE_DIRECTORY(OUT_DIR_AV18)
  DO ICH = 1, SIZE(CHANNELS)
    CHANNEL_NAME = GET_CHANNEL_NAME(CHANNELS(ICH))
    OPEN(10, FILE=OUT_DIR_AV18//"delta_"//TRIM(CHANNEL_NAME)//".dat", STATUS="REPLACE")
    DO IE = 1, NE
      WRITE(10, *) ENERGIES(IE), PHASE_SHIFTS(ICH, IE)%delta1_S, &
        PHASE_SHIFTS(ICH, IE)%delta2_S, PHASE_SHIFTS(ICH, IE)%epsilon_S
    END DO
    CLOSE(10)
  ENDDO

  CALL RESET_SCATTERING_NN_VARIATIONAL

  CALL NN_SCATTERING_VARIATIONAL_ENERGIES_CHANNELS(ENERGIES, CHANNELS, LEMP, PHASE_SHIFTS, IPOT = 19, ILB = 15)

  ! Output results to files
  ! Create output directory if it doesn't exist
  CALL CREATE_DIRECTORY(OUT_DIR_EFT_15)
  DO ICH = 1, SIZE(CHANNELS)
    CHANNEL_NAME = GET_CHANNEL_NAME(CHANNELS(ICH))
    OPEN(10, FILE=OUT_DIR_EFT_15//"delta_"//TRIM(CHANNEL_NAME)//".dat", STATUS="REPLACE")
    DO IE = 1, NE
      WRITE(10, *) ENERGIES(IE), PHASE_SHIFTS(ICH, IE)%delta1_S, &
        PHASE_SHIFTS(ICH, IE)%delta2_S, PHASE_SHIFTS(ICH, IE)%epsilon_S
    END DO
    CLOSE(10)
  ENDDO

  CALL RESET_SCATTERING_NN_VARIATIONAL
  CALL SET_DYNAMIC(.TRUE.)
  LECS_15 = GET_LECS(15)
  CALL SET_ENERGIES(ENERGIES)
  CALL SET_CHANNELS(CHANNELS)
  CALL SET_NEW_LECS(LECS_15)
  CALL NN_SCATTERING_VARIATIONAL_ENERGIES_CHANNELS(ENERGIES, CHANNELS, LEMP, PHASE_SHIFTS, LECS_FOR_PLESS = LECS_15)

  ! Output results to files
  ! Create output directory if it doesn't exist
  CALL CREATE_DIRECTORY(OUT_DIR_EFT_15_DYNAMIC)
  DO ICH = 1, SIZE(CHANNELS)
    CHANNEL_NAME = GET_CHANNEL_NAME(CHANNELS(ICH))
    OPEN(10, FILE=OUT_DIR_EFT_15_DYNAMIC//"delta_"//TRIM(CHANNEL_NAME)//".dat", STATUS="REPLACE")
    DO IE = 1, NE
      WRITE(10, *) ENERGIES(IE), PHASE_SHIFTS(ICH, IE)%delta1_S, &
        PHASE_SHIFTS(ICH, IE)%delta2_S, PHASE_SHIFTS(ICH, IE)%epsilon_S
    END DO
    CLOSE(10)
  ENDDO


  DEALLOCATE(CHANNELS)
  DEALLOCATE(PHASE_SHIFTS)
  CALL RESET_SCATTERING_NN_VARIATIONAL

END PROGRAM TEST_NN_SCATTERING_VARIATIONAL_ENERGIES_CHANNELS