PROGRAM FIT_LOW_ENERGY_OBSERVABLES
  USE SCATTERING_NN_VARIATIONAL
  USE QUANTUM_NUMBERS
  IMPLICIT NONE
  INTEGER, PARAMETER :: LMAX = 2
  INTEGER, PARAMETER :: JMAX = 2
  INTEGER, PARAMETER :: TZ = 0
  INTEGER, PARAMETER :: FIT_ORDER = 2
  CHARACTER(LEN=*), PARAMETER :: AV18_DIR = "output/AV18/"
  CHARACTER(LEN=*), PARAMETER :: EFT_PLESS_15_DIR = "output/EFT_pless_15/"
  TYPE(SCATTERING_CHANNEL), ALLOCATABLE :: CHANNELS(:) 
  INTEGER :: NCHANNELS, ICH
  CHARACTER(LEN=8) :: CHANNEL_NAME
  INTEGER :: IE, NDATA, IOS, IEQ
  CHARACTER(LEN=256) :: LINE
  REAL(8), ALLOCATABLE :: ENERGIES(:)
  TYPE(PHASE_SHIFT_RESULT), ALLOCATABLE :: PHASE_SHIFT_ARRAY(:)
  DOUBLE PRECISION :: CONST_RESULT(2,FIT_ORDER+1)
  DOUBLE PRECISION, ALLOCATABLE :: K2(:), KCOTD(:,:)


  ! AV18 TEST
  PRINT *, "Testing AV18 potential..."
  CALL PREPARE_CHANNELS(LMAX, JMAX, TZ, CHANNELS)
  NCHANNELS = SIZE(CHANNELS)
  DO ICH = 1, NCHANNELS
    WRITE(*,*) "========================================================"
    CHANNEL_NAME = GET_CHANNEL_NAME(CHANNELS(ICH))
    PRINT *, "  Channel: ", CHANNEL_NAME
    OPEN(UNIT=10, FILE=TRIM(AV18_DIR)//"delta_"//TRIM(CHANNEL_NAME)//".dat", STATUS='OLD', ACTION='READ')

    ! First, count the number of data lines (not starting with #)
    NDATA = 0
    DO
      READ(10, '(A)', IOSTAT=IOS) LINE
      IF (IOS /= 0) EXIT
      IF (LEN_TRIM(LINE) == 0) CYCLE
      LINE = ADJUSTL(LINE)
      IF (LINE(1:1) == "#") CYCLE
      NDATA = NDATA + 1
    END DO
    REWIND(10)

    IF (ALLOCATED(ENERGIES)) THEN
      DEALLOCATE(ENERGIES)
    END IF
    ALLOCATE(ENERGIES(NDATA))
    IF (ALLOCATED(PHASE_SHIFT_ARRAY)) THEN
      DEALLOCATE(PHASE_SHIFT_ARRAY)
    END IF
    ALLOCATE(PHASE_SHIFT_ARRAY(NDATA))
    IF (ALLOCATED(K2)) THEN
      DEALLOCATE(K2)
    END IF
    ALLOCATE(K2(NDATA))
    IF (ALLOCATED(KCOTD)) THEN
      DEALLOCATE(KCOTD)
    END IF
    ALLOCATE(KCOTD(2,NDATA))

    WRITE(*,*) "  Number of data points: ", NDATA
    IE = 0
    DO
      READ(10, '(A)', IOSTAT=IOS) LINE
      IF (IOS /= 0) EXIT
      IF (LEN_TRIM(LINE) == 0) CYCLE
      LINE = ADJUSTL(LINE)
      IF (LINE(1:1) == "#") CYCLE
      IE = IE + 1
      READ(LINE, *) ENERGIES(IE), PHASE_SHIFT_ARRAY(IE)%delta1_BB, &
            PHASE_SHIFT_ARRAY(IE)%delta2_BB, PHASE_SHIFT_ARRAY(IE)%epsilon_BB
    END DO

    CONST_RESULT = 0.0D0
    CALL FIT_CHANNEL_LOW_ENERGY(CHANNELS(ICH), ENERGIES, PHASE_SHIFT_ARRAY, CONST_RESULT, FIT_ORDER, K2, KCOTD)
    WRITE(*,*) "  Fitted constants for channel ", CHANNEL_NAME, ":"
    DO IEQ = 1, GET_CHANNEL_NCH(CHANNELS(ICH))
      IF (IEQ==2) WRITE(*,*)
      WRITE(*,'(A)', ADVANCE='NO') "    Fit: "
      DO IE = 1, FIT_ORDER+1
        IF (IE > 1) WRITE(*,'(A)', ADVANCE='NO') " + "
        IF (IE == 1) THEN
          WRITE(*,'(F12.6)', ADVANCE='NO') CONST_RESULT(IEQ,IE)
        ELSE
          WRITE(*,'(F12.6,A,I0)', ADVANCE='NO') CONST_RESULT(IEQ, IE), " * X"
          IF (IE > 2) WRITE(*,'(A,I0)', ADVANCE='NO') "**", IE-1
        END IF
      END DO 
    ENDDO
    WRITE(*,*)
    CLOSE(UNIT=10)
  ENDDO ! ICH



END PROGRAM FIT_LOW_ENERGY_OBSERVABLES