MODULE ANGLES
  IMPLICIT NONE
  PRIVATE
  
  DOUBLE PRECISION, PARAMETER :: PI = 4.D0*DATAN(1.D0)
  DOUBLE PRECISION, PARAMETER :: ONEEIGHTY_OVER_PI = 180.D0 / PI
  DOUBLE PRECISION, PARAMETER :: PI_OVER_ONEEIGHTY = PI / 180.D0


  PUBLIC :: DEG_TO_RAD, RAD_TO_DEG
  PUBLIC :: PI, ONEEIGHTY_OVER_PI, PI_OVER_ONEEIGHTY

CONTAINS

  !> Converts an angle in degrees to radians.
  !! \param[in] DEG Angle in degrees.
  !! \return Angle in radians.
  FUNCTION DEG_TO_RAD(DEG) RESULT(RAD)
    DOUBLE PRECISION, INTENT(IN) :: DEG
    DOUBLE PRECISION :: RAD

    RAD = DEG * PI_OVER_ONEEIGHTY
  END FUNCTION DEG_TO_RAD

  !> Converts an angle in radians to degrees.
  !! \param[in] RAD Angle in radians.
  !! \return Angle in degrees.
  FUNCTION RAD_TO_DEG(RAD) RESULT(DEG)
    DOUBLE PRECISION, INTENT(IN) :: RAD
    DOUBLE PRECISION :: DEG

    DEG = RAD * ONEEIGHTY_OVER_PI
  END FUNCTION RAD_TO_DEG

END MODULE ANGLES