MODULE NUMBER_DIFFERENCES
  IMPLICIT NONE
  PRIVATE

  PUBLIC :: ABS_DIFF_PROCENT
  PUBLIC :: ABS_DIFF_RELATIVE
  PUBLIC :: ABS_DIFF

CONTAINS
  FUNCTION ABS_DIFF_PROCENT(NUM, REF, TOLERANCE, THRESHOLD) RESULT(DIFF)
    DOUBLE PRECISION, INTENT(IN) :: NUM, REF
    DOUBLE PRECISION, INTENT(IN), OPTIONAL :: TOLERANCE, THRESHOLD
    DOUBLE PRECISION :: DIFF, TOLERANCE_, THRESHOLD_

    TOLERANCE_ = 1.D-10
    THRESHOLD_ = 0.D0
    
    DIFF = ABS_DIFF_RELATIVE(NUM, REF, TOLERANCE_, THRESHOLD_)
    DIFF = DIFF * 100.0D0
  END FUNCTION ABS_DIFF_PROCENT

  FUNCTION ABS_DIFF_RELATIVE(NUM, REF, TOLERANCE, THRESHOLD) RESULT(DIFF)
    DOUBLE PRECISION, INTENT(IN) :: NUM, REF
    DOUBLE PRECISION, INTENT(IN), OPTIONAL :: TOLERANCE, THRESHOLD
    DOUBLE PRECISION :: DIFF, TOLERANCE_, THRESHOLD_

    TOLERANCE_ = 1.D-10
    THRESHOLD_ = 0.D0
    IF (PRESENT(TOLERANCE)) THEN
      TOLERANCE_ = TOLERANCE
    END IF
    IF (PRESENT(THRESHOLD)) THEN
      THRESHOLD_ = THRESHOLD
    END IF

    IF (ABS(NUM) < THRESHOLD_ .AND. ABS(REF) < THRESHOLD_) THEN
      DIFF = 0.D0
    ELSEIF (ABS(NUM) < THRESHOLD_ .AND. ABS(REF) >= THRESHOLD_ .OR. &
             ABS(NUM) >= THRESHOLD_ .AND. ABS(REF) < THRESHOLD_) THEN
      DIFF = 1.D0
    ELSE
      DIFF = ABS_DIFF(NUM - REF, THRESHOLD_) / MAX(ABS(REF), TOLERANCE_)
    END IF

  END FUNCTION ABS_DIFF_RELATIVE
    

  FUNCTION ABS_DIFF(A, B, THRESHOLD) RESULT(DIFF)
    DOUBLE PRECISION, INTENT(IN) :: A, B
    DOUBLE PRECISION, INTENT(IN), OPTIONAL :: THRESHOLD
    DOUBLE PRECISION :: DIFF, THRESHOLD_

    THRESHOLD_ = 0.D0
    IF (PRESENT(THRESHOLD)) THEN
      THRESHOLD_ = THRESHOLD
    END IF

    IF (ABS(A) < THRESHOLD_ .AND. ABS(B) < THRESHOLD_) THEN
      DIFF = 0.D0
    ELSE
      DIFF = ABS(A - B)
    ENDIF
  END FUNCTION ABS_DIFF

END MODULE NUMBER_DIFFERENCES