!   CLO( 0)  => c10
!   CLO( 1)  => c01
!   CNLO(1)  => c2c00
!   CNLO(2)  => c2c10
!   CNLO(3)  => c2c01
!   CNLO(4)  => c2c11
!   CNLO(5)  => c2t0
!   CNLO(6)  => c2t1
!   CNLO(7)  => c2b
!   CIT( 0)  => c0ct

MODULE EFT_PLESS
  USE REALLOCATE_UTILS
  USE QUANTUM_NUMBERS
  USE QUANTUM_OPERATORS
  IMPLICIT NONE
  PRIVATE

  DOUBLE PRECISION, PARAMETER :: HTC = 197.32697D0

  TYPE, PUBLIC :: LECS_EFT_PLESS
    INTEGER :: ILB = -1
    INTEGER :: ORDER = -1
    DOUBLE PRECISION :: RC(0:1,0:1) = 0.D0
    DOUBLE PRECISION :: CLO(0:1)   = 0.D0
    DOUBLE PRECISION :: CNLO(7) = 0.D0
    DOUBLE PRECISION :: CN3LO(11)= 0.D0
    DOUBLE PRECISION :: CIT(0:4)= 0.D0
  END TYPE LECS_EFT_PLESS

  TYPE, PUBLIC :: EFT_RADIAL_FUNCTIONS
    INTEGER :: ORDER
    DOUBLE PRECISION, ALLOCATABLE :: RC
    DOUBLE PRECISION, ALLOCATABLE :: FR_I(:,:)
  END TYPE EFT_RADIAL_FUNCTIONS

  INTERFACE SET_LECS
    MODULE PROCEDURE SET_LECS_FROM_LECS
    MODULE PROCEDURE SET_LECS_SINGLE
    MODULE PROCEDURE SET_LECS_ILB
  END INTERFACE

  LOGICAL, PRIVATE :: FIRST_CALL = .TRUE., LECS_SET = .FALSE., LECS_ALL_SET = .FALSE.
  INTEGER :: NMODELS = -1
  TYPE(LECS_EFT_PLESS), ALLOCATABLE :: LECS_ALL(:)
  TYPE(LECS_EFT_PLESS) :: LECS
  TYPE(SCATTERING_CHANNEL) :: CHANNEL
  INTEGER :: ORDER =-1

  INTEGER          :: I2   (2,2)
  INTEGER          :: LS   (2,2)
  INTEGER          :: L2   (2,2)
  DOUBLE PRECISION :: S12  (2,2)
  INTEGER          :: T12

  PUBLIC :: EFT_PLESS_PW, LECS_TO_ST_LECS, ST_LECTS_TO_LECS
  PUBLIC :: SET_LECS, GET_LECS, PRINT_LECS
  PUBLIC :: GET_EFT_RADIAL_FUNCTIONS

  PRIVATE:: CR, EFT_RADIAL_1, EFT_RADIAL_2, EFT_RADIAL_3, EFT_RADIAL_4, EFT_RADIAL_5, EFT_RADIAL_6, EFT_RADIAL_7
  PRIVATE:: SET_LECS_FROM_LECS, SET_LECS_SINGLE, SET_ALL_LECS, SET_LECS_ILB
  PRIVATE:: SET_OPERATORS
  PRIVATE:: PREPARE

CONTAINS
  SUBROUTINE SET_LECS_FROM_LECS(LECS_IN)
    IMPLICIT NONE
    TYPE(LECS_EFT_PLESS), INTENT(IN) :: LECS_IN
    LECS = LECS_IN
    LECS_SET = .TRUE.
  END SUBROUTINE SET_LECS_FROM_LECS

  SUBROUTINE SET_LECS_SINGLE(R00, R10, R01, R11, C10, C01, C200, C201, C210, C211, C2T0, C2T1, C2B, &
    C400, C410, C401, C411, C4T0, C4T1, C4B0, C4B1, C4BB0, C4BB1, C4Q, &
    CIT0, CIT1, CIT2, CIT3, CIT4)
    IMPLICIT NONE
    DOUBLE PRECISION, OPTIONAL, INTENT(IN) :: R00, R10, R01, R11
    DOUBLE PRECISION, OPTIONAL, INTENT(IN) :: C10, C01
    DOUBLE PRECISION, OPTIONAL, INTENT(IN) :: C200, C201, C210, C211, C2T0, C2T1, C2B
    DOUBLE PRECISION, OPTIONAL, INTENT(IN) :: C400, C410, C401, C411, C4T0, C4T1, C4B0, C4B1, C4BB0, C4BB1, C4Q
    DOUBLE PRECISION, OPTIONAL, INTENT(IN) :: CIT0, CIT1, CIT2, CIT3, CIT4
    LOGICAL :: AT_LEAST_ONE_LEC_IS_NOT_NULL

    IF (.NOT.(PRESENT(R00) .OR. PRESENT(R10) .OR. PRESENT(R01) .OR. PRESENT(R11))) THEN
      STOP "AT LEAST ONE OF R MUST BE PRESENT"
    END IF
    IF (.NOT.(PRESENT(C10) .OR. PRESENT(C01) .OR. PRESENT(C200) .OR. PRESENT(C201) .OR. PRESENT(C210) .OR. &
          PRESENT(C211) .OR. PRESENT(C2T0) .OR. PRESENT(C2T1) .OR. PRESENT(C2B) .OR. PRESENT(C400) .OR. &
          PRESENT(C410) .OR. PRESENT(C401) .OR. PRESENT(C411) .OR. PRESENT(C4T0) .OR. PRESENT(C4T1) .OR. &
          PRESENT(C4B0) .OR. PRESENT(C4B1) .OR. PRESENT(C4BB0) .OR. PRESENT(C4BB1) .OR. PRESENT(C4Q) .OR. &
          PRESENT(CIT0) .OR. PRESENT(CIT1) .OR. PRESENT(CIT2) .OR. PRESENT(CIT3) .OR. PRESENT(CIT4))) THEN
      STOP "AT LEAST ONE C MUST BE PRESENT"
    END IF
    AT_LEAST_ONE_LEC_IS_NOT_NULL = .FALSE.
    IF (PRESENT(C10))  THEN
      IF (C10 /= 0.D0) AT_LEAST_ONE_LEC_IS_NOT_NULL = .TRUE.
    END IF
    IF (PRESENT(C01))  THEN
      IF (C01 /= 0.D0) AT_LEAST_ONE_LEC_IS_NOT_NULL = .TRUE.
    END IF
    IF (PRESENT(C200)) THEN
      IF (C200 /= 0.D0) AT_LEAST_ONE_LEC_IS_NOT_NULL = .TRUE.
    END IF
    IF (PRESENT(C201)) THEN
      IF (C201 /= 0.D0) AT_LEAST_ONE_LEC_IS_NOT_NULL = .TRUE.
    END IF
    IF (PRESENT(C210)) THEN
      IF (C210 /= 0.D0) AT_LEAST_ONE_LEC_IS_NOT_NULL = .TRUE.
    END IF
    IF (PRESENT(C211)) THEN
      IF (C211 /= 0.D0) AT_LEAST_ONE_LEC_IS_NOT_NULL = .TRUE.
    END IF
    IF (PRESENT(C2T0)) THEN
      IF (C2T0 /= 0.D0) AT_LEAST_ONE_LEC_IS_NOT_NULL = .TRUE.
    END IF
    IF (PRESENT(C2T1)) THEN
      IF (C2T1 /= 0.D0) AT_LEAST_ONE_LEC_IS_NOT_NULL = .TRUE.
    END IF
    IF (PRESENT(C2B))  THEN
      IF (C2B /= 0.D0) AT_LEAST_ONE_LEC_IS_NOT_NULL = .TRUE.
    END IF
    IF (PRESENT(C400)) THEN
      IF (C400 /= 0.D0) AT_LEAST_ONE_LEC_IS_NOT_NULL = .TRUE.
    END IF
    IF (PRESENT(C410)) THEN
      IF (C410 /= 0.D0) AT_LEAST_ONE_LEC_IS_NOT_NULL = .TRUE.
    END IF
    IF (PRESENT(C401)) THEN
      IF (C401 /= 0.D0) AT_LEAST_ONE_LEC_IS_NOT_NULL = .TRUE.
    END IF
    IF (PRESENT(C411)) THEN
      IF (C411 /= 0.D0) AT_LEAST_ONE_LEC_IS_NOT_NULL = .TRUE.
    END IF
    IF (PRESENT(C4T0)) THEN
      IF (C4T0 /= 0.D0) AT_LEAST_ONE_LEC_IS_NOT_NULL = .TRUE.
    END IF
    IF (PRESENT(C4T1)) THEN
      IF (C4T1 /= 0.D0) AT_LEAST_ONE_LEC_IS_NOT_NULL = .TRUE.
    END IF
    IF (PRESENT(C4B0)) THEN
      IF (C4B0 /= 0.D0) AT_LEAST_ONE_LEC_IS_NOT_NULL = .TRUE.
    END IF
    IF (PRESENT(C4B1)) THEN
      IF (C4B1 /= 0.D0) AT_LEAST_ONE_LEC_IS_NOT_NULL = .TRUE.
    END IF
    IF (PRESENT(C4BB0)) THEN
      IF (C4BB0 /= 0.D0) AT_LEAST_ONE_LEC_IS_NOT_NULL = .TRUE.
    END IF
    IF (PRESENT(C4BB1)) THEN
      IF (C4BB1 /= 0.D0) AT_LEAST_ONE_LEC_IS_NOT_NULL = .TRUE.
    END IF
    IF (PRESENT(C4Q)) THEN
      IF (C4Q /= 0.D0) AT_LEAST_ONE_LEC_IS_NOT_NULL = .TRUE.
    END IF
    IF (PRESENT(CIT0)) THEN
      IF (CIT0 /= 0.D0) AT_LEAST_ONE_LEC_IS_NOT_NULL = .TRUE.
    END IF
    IF (PRESENT(CIT1)) THEN
      IF (CIT1 /= 0.D0) AT_LEAST_ONE_LEC_IS_NOT_NULL = .TRUE.
    END IF
    IF (PRESENT(CIT2)) THEN
      IF (CIT2 /= 0.D0) AT_LEAST_ONE_LEC_IS_NOT_NULL = .TRUE.
    END IF
    IF (PRESENT(CIT3)) THEN
      IF (CIT3 /= 0.D0) AT_LEAST_ONE_LEC_IS_NOT_NULL = .TRUE.
    END IF
    IF (PRESENT(CIT4)) THEN
      IF (CIT4 /= 0.D0) AT_LEAST_ONE_LEC_IS_NOT_NULL = .TRUE.
    END IF


    IF (PRESENT(R00)) LECS%RC(0,0) = R00
    IF (PRESENT(R10)) LECS%RC(1,0) = R10
    IF (PRESENT(R01)) LECS%RC(0,1) = R01
    IF (PRESENT(R11)) LECS%RC(1,1) = R11

    IF (PRESENT(C10)) LECS%CLO(0) = C10
    IF (PRESENT(C01)) LECS%CLO(1) = C01

    IF (PRESENT(C200)) LECS%CNLO(1) = C200
    IF (PRESENT(C201)) LECS%CNLO(2) = C201
    IF (PRESENT(C210)) LECS%CNLO(3) = C210
    IF (PRESENT(C211)) LECS%CNLO(4) = C211
    IF (PRESENT(C2T0)) LECS%CNLO(5) = C2T0
    IF (PRESENT(C2T1)) LECS%CNLO(6) = C2T1
    IF (PRESENT(C2B))  LECS%CNLO(7) = C2B

    IF (PRESENT(C400))  LECS%CN3LO(1)  = C400
    IF (PRESENT(C410))  LECS%CN3LO(2)  = C410
    IF (PRESENT(C401))  LECS%CN3LO(3)  = C401
    IF (PRESENT(C411))  LECS%CN3LO(4)  = C411
    IF (PRESENT(C4T0))  LECS%CN3LO(5)  = C4T0
    IF (PRESENT(C4T1))  LECS%CN3LO(6)  = C4T1
    IF (PRESENT(C4B0))  LECS%CN3LO(7)  = C4B0
    IF (PRESENT(C4B1))  LECS%CN3LO(8)  = C4B1
    IF (PRESENT(C4BB0)) LECS%CN3LO(9)  = C4BB0
    IF (PRESENT(C4BB1)) LECS%CN3LO(10) = C4BB1
    IF (PRESENT(C4Q))   LECS%CN3LO(11) = C4Q

    IF (PRESENT(CIT0)) LECS%CIT(0) = CIT0
    IF (PRESENT(CIT1)) LECS%CIT(1) = CIT1
    IF (PRESENT(CIT2)) LECS%CIT(2) = CIT2
    IF (PRESENT(CIT3)) LECS%CIT(3) = CIT3
    IF (PRESENT(CIT4)) LECS%CIT(4) = CIT4

    CALL SET_LECS_ORDER(LECS)
    LECS_SET = .TRUE.
  END SUBROUTINE SET_LECS_SINGLE

  SUBROUTINE SET_ALL_LECS
    IMPLICIT NONE
    INTEGER :: I, IOS
    CHARACTER(LEN=256) :: FILENAME
    INTEGER :: UNIT
    INTEGER :: ILB
    DOUBLE PRECISION :: RC(0:1,0:1), CLO(0:1), CNLO(7), CN3LO(11), CIT(0:4)

    IF (LECS_ALL_SET) RETURN

    ! Set the filename (you can change this as needed)
    FILENAME = './src/libs/physics/potentials/lecs_eft.dat'

    ! Open the file
    UNIT = 100
    OPEN(NEWUNIT=UNIT, FILE=FILENAME, STATUS='OLD', ACTION='READ', IOSTAT=IOS)
    IF (ios /= 0) THEN
      PRINT *, 'Error opening file: ', TRIM(FILENAME),"   ->   ", ios
      STOP
    END IF

    ! Read the number of lines (number of LECS)
    READ(UNIT, *, IOSTAT=IOS) NMODELS
    IF (IOS /= 0) THEN
      PRINT *, 'Error reading number of lines from file.'
      CLOSE(UNIT)
      STOP
    END IF

    ! ALLOCATE THE ARRAY
    IF (ALLOCATED(LECS_ALL)) DEALLOCATE(LECS_ALL)
    ALLOCATE(LECS_ALL(NMODELS))

    ! Read each LECS_EFT_PLESS entry
    DO I = 1, NMODELS
      READ(UNIT, *, IOSTAT=IOS) ILB, RC(0,0), RC(1,0), RC(0,1), RC(1,1), CLO(1), CLO(0), CNLO, CN3LO, CIT
      LECS_ALL(I)%ILB = ILB
      LECS_ALL(I)%RC  = RC
      LECS_ALL(I)%CLO = CLO
      LECS_ALL(I)%CNLO = CNLO
      LECS_ALL(I)%CN3LO = CN3LO
      LECS_ALL(I)%CIT = CIT
      CALL SET_LECS_ORDER(LECS_ALL(I))
      IF (IOS /= 0) THEN
        PRINT *, 'Error reading LECS entry at line ', i
        CLOSE(UNIT)
        STOP
      END IF
    END DO
    CLOSE(UNIT)
    LECS_ALL_SET = .TRUE.
  END SUBROUTINE

  SUBROUTINE SET_LECS_ORDER(LECS_IN)
    IMPLICIT NONE
    TYPE(LECS_EFT_PLESS), INTENT(INOUT) :: LECS_IN
    INTEGER :: I, J
    INTEGER :: NLO = SIZE(LECS_IN%CNLO)
    INTEGER :: N3LO = SIZE(LECS_IN%CN3LO)

    LECS_IN%ORDER = 0
    DO I=1, NLO
      IF (LECS_IN%CNLO(I) /= 0.D0) LECS_IN%ORDER = 1
    ENDDO

    DO J=1, N3LO
      IF (LECS_IN%CN3LO(J) /= 0.D0) LECS_IN%ORDER = 3
    ENDDO

  END SUBROUTINE SET_LECS_ORDER

  SUBROUTINE SET_LECS_ILB(ILB)
    IMPLICIT NONE
    INTEGER, INTENT(IN) :: ILB
    IF (ILB <= 0 .AND. ILB > NMODELS) THEN
      WRITE(*,*) "THIS MODEL (ILB) IS NOT RECOGNIZED"
      STOP
    ENDIF
    LECS = LECS_ALL(ILB)
    LECS_SET = .TRUE.
  END SUBROUTINE SET_LECS_ILB

  SUBROUTINE SET_OPERATORS()
    IMPLICIT NONE
    INTEGER :: L, S, J, T, TZ, I

    I2 = 0
    DO I=1, 2
      I2(I,I) = 1
    ENDDO

    L = GET_CHANNEL_L (CHANNEL, 1)
    S = GET_CHANNEL_S (CHANNEL, 1)
    T = GET_CHANNEL_T (CHANNEL, 1)
    TZ= GET_CHANNEL_TZ(CHANNEL)
    J = GET_CHANNEL_J (CHANNEL)

    S12   = S12_OPERATOR(L, S, J)
    LS    = LS_OPERATOR (L, S, J)
    L2    = L2_OPERATOR (L)
    T12 = T12_OPERATOR       (T,TZ)

  END SUBROUTINE SET_OPERATORS



  SUBROUTINE PREPARE(ILB)
    IMPLICIT NONE
    DOUBLE PRECISION, PARAMETER :: MINR = 1.D-1, ZERO = 1.D-10
    INTEGER, INTENT(IN) :: ILB
    LECS%ILB = ILB
    CALL SET_LECS_ILB(ILB)
    CALL SET_OPERATORS
    IF (SUM(ABS(LECS%RC)) < MINR) STOP "RC not set"
  END SUBROUTINE PREPARE

  SUBROUTINE EFT_PLESS_PW(ILB, L, S, J, T1Z, T2Z, R, VPW, LEMP)
    IMPLICIT NONE
    INTEGER, INTENT(IN) :: ILB, L, S, J, T1Z, T2Z, LEMP
    DOUBLE PRECISION, INTENT(IN) :: R
    DOUBLE PRECISION, INTENT(OUT):: VPW(2,2)
    INTEGER :: T, TZ
    TYPE(SCATTERING_CHANNEL) :: CHANNEL_NEW
    LOGICAL :: IS_NEW_CHANNEL
    DOUBLE PRECISION :: RC
    INTEGER :: LS2(2,2)

    VPW = 0
    TZ = (T1Z+T2Z)/2
    T = MOD(MOD((L+S),2)+1,2)
    CALL SET_CHANNEL(CHANNEL_NEW, J, L, S, TZ)
    IS_NEW_CHANNEL = .NOT.IS_SAME_CHANNEL(CHANNEL, CHANNEL_NEW)
    CHANNEL = CHANNEL_NEW

    IF (FIRST_CALL) THEN
      CALL SET_ALL_LECS
      CALL PREPARE(ILB)
      FIRST_CALL = .FALSE.
    ELSEIF (IS_NEW_CHANNEL) THEN
      CALL PREPARE(ILB)
    ENDIF

    RC = LECS%RC(S,T)
    ORDER = LECS%ORDER

    IF ( S==0 .AND. T==0 ) THEN
      SELECT CASE (ORDER)
      CASE (0)
        RETURN
      CASE (1)
        VPW = LECS%CNLO(1) * EFT_RADIAL_1(R, RC) * I2
      CASE (3)
        VPW = LECS%CNLO(1) * EFT_RADIAL_1(R, RC) * I2
        VPW = VPW + LECS%CN3LO(1)  * EFT_RADIAL_4(R, RC) *I2 &
                  + LECS%CN3LO(10) * EFT_RADIAL_7(R, RC) *L2
      CASE DEFAULT
        STOP "ERROR IN EFT_PLESS_PW:: S=0 AND T=0"
      END SELECT
    ENDIF

    IF ( S==1 .AND. T==0 ) THEN
      SELECT CASE (ORDER)
      CASE (0)
        VPW = LECS%CLO(T) * I2
      CASE (1)
        VPW = LECS%CLO(T) * I2
        VPW = VPW + LECS%CNLO(2) * EFT_RADIAL_1(R, RC) * I2 &
                  + LECS%CNLO(5) * EFT_RADIAL_2(R, RC) * S12 &
                  + LECS%CNLO(7) * EFT_RADIAL_3(R, RC) * LS
      CASE (3)
        LS2 = MATMUL(LS, LS)
        VPW = LECS%CLO(T) * I2
        VPW = VPW + LECS%CNLO(2) * EFT_RADIAL_1(R, RC) * I2 &
                  + LECS%CNLO(5) * EFT_RADIAL_2(R, RC) * S12 &
                  + LECS%CNLO(7) * EFT_RADIAL_3(R, RC) * LS
        VPW = VPW + LECS%CN3LO(2) * EFT_RADIAL_4(R, RC) * I2 &
                  + LECS%CN3LO(5) * EFT_RADIAL_5(R, RC) * S12 &
                  + LECS%CN3LO(7) * EFT_RADIAL_6(R, RC) * LS &
                  + LECS%CN3LO(9) * EFT_RADIAL_7(R, RC) * LS2 &
                  + LECS%CN3LO(11)* EFT_RADIAL_7(R, RC) * L2
      CASE DEFAULT
        STOP "ERROR IN EFT_PLESS_PW:: S=1 AND T=0"
      END SELECT
    ENDIF

    IF ( S==0 .AND. T==1 ) THEN
      SELECT CASE (ORDER)
      CASE (0)
        VPW = LECS%CLO(T) * I2
      CASE (1)
        VPW = LECS%CLO(T) * I2
        VPW = VPW + LECS%CNLO(3) * EFT_RADIAL_1(R, RC) * I2 &
                  + LECS%CIT(0)                * T12 * I2
      CASE (3)
        VPW = LECS%CLO(T) * I2
        VPW = VPW + LECS%CNLO(3)  * EFT_RADIAL_1(R, RC) * I2 &
                  + LECS%CIT(0)                 * T12 * I2
        VPW = VPW + LECS%CN3LO(3) * EFT_RADIAL_4(R, RC)     * I2 &
                  + LECS%CN3LO(10)* EFT_RADIAL_7(R, RC)     * L2 &
                  + LECS%CIT(1)   * EFT_RADIAL_1(R, RC)     * T12 * I2
      CASE DEFAULT
        STOP "ERROR IN EFT_PLESS_PW:: S=0 AND T=1"
      END SELECT
    ENDIF

    IF ( S==1 .AND. T==1 ) THEN
      SELECT CASE (ORDER)
      CASE (0)
        RETURN
      CASE (1)
        VPW =   LECS%CNLO(4) * EFT_RADIAL_1(R, RC) *  I2 &
              + LECS%CNLO(6) * EFT_RADIAL_2(R, RC) *  S12 &
              + LECS%CNLO(7) * EFT_RADIAL_3(R, RC) *  LS &
              + LECS%CIT(0)                *  T12 * I2
      CASE (3)
        LS2 = MATMUL(LS, LS)
        VPW =   LECS%CNLO(4) * EFT_RADIAL_1(R, RC) *  I2 &
              + LECS%CNLO(6) * EFT_RADIAL_2(R, RC) *  S12 &
              + LECS%CNLO(7) * EFT_RADIAL_3(R, RC) *  LS &
              + LECS%CIT(0)                *  T12 * I2
        VPW =   VPW &
              + LECS%CN3LO(4) * EFT_RADIAL_4(R, RC)    * I2 &
              + LECS%CN3LO(6) * EFT_RADIAL_5(R, RC)    * S12 &
              + LECS%CN3LO(8) * EFT_RADIAL_6(R, RC)    * LS &
              + LECS%CN3LO(9) * EFT_RADIAL_7(R, RC)    * LS2 &
              + LECS%CN3LO(11)* EFT_RADIAL_7(R, RC)    * L2 &
              +(  LECS%CIT(2) * EFT_RADIAL_1(R, RC)    * I2  + &
                  LECS%CIT(3) * EFT_RADIAL_2(R, RC)    * S12 + &
                  LECS%CIT(4) * EFT_RADIAL_3(R, RC)    * LS    &
                                                        ) * T12
      CASE DEFAULT
        STOP "ERROR IN EFT_PLESS_PW:: S=1 AND T=1"
      END SELECT
    ENDIF

    VPW = VPW * CR(R, RC)
    VPW = VPW * HTC

    IF (GET_CHANNEL_NCH(CHANNEL) == 1 ) THEN
      VPW(1,2) = 0.D0
      VPW(2,1) = 0.D0
      VPW(2,2) = 0.D0
    ENDIF
    RETURN
  END SUBROUTINE EFT_PLESS_PW


  PURE ELEMENTAL FUNCTION CR(R, RC) RESULT(CR_OUT)
    IMPLICIT NONE
    DOUBLE PRECISION, PARAMETER :: PI = 4.D0*DATAN(1.D0)
    DOUBLE PRECISION, INTENT(IN) :: R, RC
    DOUBLE PRECISION :: CR_OUT
    CR_OUT = DEXP(-R**2/RC**2)/(PI**(3.D0/2.D0)*RC**3)
  END FUNCTION CR

  PURE ELEMENTAL FUNCTION EFT_RADIAL_1(R, RC) RESULT(F1)
    IMPLICIT NONE
    DOUBLE PRECISION, INTENT(IN) :: R, RC
    DOUBLE PRECISION :: F1
    F1 = (6*RC**2 - 4*R**2)/(RC**4)
  END FUNCTION EFT_RADIAL_1

  PURE ELEMENTAL FUNCTION EFT_RADIAL_2(R, RC) RESULT(F2)
    IMPLICIT NONE
    DOUBLE PRECISION, INTENT(IN) :: R, RC
    DOUBLE PRECISION :: F2
    F2 =-4*R**2/RC**4
  END FUNCTION EFT_RADIAL_2

  PURE ELEMENTAL FUNCTION EFT_RADIAL_3(R, RC) RESULT(F3)
    IMPLICIT NONE
    DOUBLE PRECISION, INTENT(IN) :: R, RC
    DOUBLE PRECISION :: F3
    F3 = 2.D0/RC**2
  END FUNCTION EFT_RADIAL_3

  PURE ELEMENTAL FUNCTION EFT_RADIAL_4(R, RC) RESULT(F4)
    IMPLICIT NONE
    DOUBLE PRECISION, INTENT(IN) :: R, RC
    DOUBLE PRECISION :: F4
    F4 = 4.D0*( 4*R**4 - 20*RC**2*R**2 + 15*RC**4 )/RC**8
  END FUNCTION EFT_RADIAL_4

  PURE ELEMENTAL FUNCTION EFT_RADIAL_5(R, RC) RESULT(F5)
    IMPLICIT NONE
    DOUBLE PRECISION, INTENT(IN) :: R, RC
    DOUBLE PRECISION :: F5
    F5 = 8*R**2*( 2*R**2 - 7*RC**2 )/RC**8
  END FUNCTION EFT_RADIAL_5

  PURE ELEMENTAL FUNCTION EFT_RADIAL_6(R, RC) RESULT(F6)
    IMPLICIT NONE
    DOUBLE PRECISION, INTENT(IN) :: R, RC
    DOUBLE PRECISION :: F6
    F6 = ( 20*RC**2 - 8*R**2 )/RC**6
  END FUNCTION EFT_RADIAL_6

  PURE ELEMENTAL FUNCTION EFT_RADIAL_7(R, RC) RESULT(F7)
    IMPLICIT NONE
    DOUBLE PRECISION, INTENT(IN) :: R, RC
    DOUBLE PRECISION :: F7
    F7 =-EFT_RADIAL_3(R, RC)**2
  END FUNCTION EFT_RADIAL_7


  PURE FUNCTION LECS_TO_ST_LECS(LECS_OLD) RESULT(ST_LECS)
    IMPLICIT NONE
    TYPE(LECS_EFT_PLESS), INTENT(IN) :: LECS_OLD
    TYPE(LECS_EFT_PLESS) :: ST_LECS
    DOUBLE PRECISION :: C(7)
    DOUBLE PRECISION :: D(11)
    DOUBLE PRECISION :: CIT(0:4)

    C   = LECS_OLD%CNLO
    D   = LECS_OLD%CN3LO
    CIT = LECS_OLD%CIT

    ST_LECS%ILB       = LECS_OLD%ILB
    ST_LECS%RC        = LECS_OLD%RC
    ST_LECS%CLO       = LECS_OLD%CLO
    ST_LECS%CNLO(1)   = C(1) - 3*C(2) - 3*C(3) + 9*C(4)
    ST_LECS%CNLO(2)   = C(1) - 3*C(2) + C(3) - 3*C(4)
    ST_LECS%CNLO(3)   = C(1) + C(2) - 3*C(3) - 3*C(4)
    ST_LECS%CNLO(4)   = C(1) + C(2) + C(3) + C(4)
    ST_LECS%CNLO(5)   = C(5) - 3*C(6)
    ST_LECS%CNLO(6)   = C(5) + C(6)
    ST_LECS%CNLO(7)   = C(7)
    ST_LECS%CN3LO( 1) = D(1) - 3*D(2) - 3*D(3) + 9*D(4)
    ST_LECS%CN3LO( 2) = D(1) - 3*D(2) + D(3) - 3*D(4)
    ST_LECS%CN3LO( 3) = D(1) + D(2) - 3*D(3) - 3*D(4)
    ST_LECS%CN3LO( 4) = D(1) + D(2) + D(3) + D(4)
    ST_LECS%CN3LO( 5) = D(5) - 3*D(6)
    ST_LECS%CN3LO( 6) = D(5) + D(6)
    ST_LECS%CN3LO( 7) = D(7) - 3*D(8)
    ST_LECS%CN3LO( 8) = D(7) + D(8)
    ST_LECS%CN3LO( 9) = D(9)
    ST_LECS%CN3LO(10) = D(10) - 3*D(11)
    ST_LECS%CN3LO(11) = D(10) + D(11)
    ST_LECS%CIT(0)    = CIT(0)
    ST_LECS%CIT(1)    = CIT(1) - 3*CIT(2)
    ST_LECS%CIT(2)    = CIT(1) + CIT(2)
    ST_LECS%CIT(3)    = CIT(3)
    ST_LECS%CIT(4)    = CIT(4)
  END FUNCTION LECS_TO_ST_LECS

  FUNCTION ST_LECTS_TO_LECS(ST_LECS) RESULT(OP_LECS)
    IMPLICIT NONE
    TYPE(LECS_EFT_PLESS), INTENT(IN) :: ST_LECS
    TYPE(LECS_EFT_PLESS) :: OP_LECS
    DOUBLE PRECISION :: C1(7)
    DOUBLE PRECISION :: D1(11)
    DOUBLE PRECISION :: CIT(0:4)

    C1   = ST_LECS%CNLO
    D1   = ST_LECS%CN3LO
    CIT  = ST_LECS%CIT

    OP_LECS%ILB= ST_LECS%ILB
    OP_LECS%RC = ST_LECS%RC
    OP_LECS%CLO = ST_LECS%CLO
    OP_LECS%CNLO(1)   = (C1(1) + 3*C1(2) + 3*C1(3) + 9*C1(4))/16.D0
    OP_LECS%CNLO(2)   = (-C1(1) - 3*C1(2) + C1(3) + 3*C1(4))/16.D0
    OP_LECS%CNLO(3)   = (-C1(1) + C1(2) - 3*C1(3) + 3*C1(4))/16.D0
    OP_LECS%CNLO(4)   = (C1(1) - C1(2) - C1(3) + C1(4))/16.D0
    OP_LECS%CNLO(5)   = (C1(5) + 3*C1(6))/4.D0
    OP_LECS%CNLO(6)   = (-C1(5) + C1(6))/4.D0
    OP_LECS%CNLO(7)   = C1(7)
    OP_LECS%CN3LO(1)  = (D1(1) + 3*(D1(2) + D1(3) + 3*D1(4)))/16.D0
    OP_LECS%CN3LO(2)  = (-D1(1) - 3*D1(2) + D1(3) + 3*D1(4))/16.D0
    OP_LECS%CN3LO(3)  = (-D1(1) + D1(2) - 3*D1(3) + 3*D1(4))/16.D0
    OP_LECS%CN3LO(4)  = (D1(1) - D1(2) - D1(3) + D1(4))/16.D0
    OP_LECS%CN3LO(5)  = (D1(5) + 3*D1(6))/4.D0
    OP_LECS%CN3LO(6)  = (-D1(5) + D1(6))/4.D0
    OP_LECS%CN3LO(7)  = (D1(7) + 3*D1(8))/4.D0
    OP_LECS%CN3LO(8)  = (-D1(7) + D1(8))/4.D0
    OP_LECS%CN3LO(9)  = D1(9)
    OP_LECS%CN3LO(10) = (D1(10) + 3*D1(11))/4.D0
    OP_LECS%CN3LO(11) = (-D1(10) + D1(11))/4.D0
    OP_LECS%CIT(0)    = CIT(0)
    OP_LECS%CIT(1)    = (CIT(1) + 3*CIT(2))/4.D0
    OP_LECS%CIT(2)    = (-CIT(1) + CIT(2))/4.D0
    OP_LECS%CIT(3)    = CIT(3)
    OP_LECS%CIT(4)    = CIT(4)
  END FUNCTION ST_LECTS_TO_LECS

  FUNCTION GET_LECS(ILB) RESULT(LECS_OUT)
    IMPLICIT NONE
    INTEGER, INTENT(IN) :: ILB
    TYPE(LECS_EFT_PLESS) :: LECS_OUT

    IF (.NOT.LECS_SET) CALL SET_ALL_LECS

    IF (ILB <= 0 .AND. ILB > NMODELS) THEN
      WRITE(*,*) "THIS MODEL (ILB) IS NOT RECOGNIZED"
      STOP
    ENDIF
    LECS_OUT = LECS_ALL(ILB)
  END FUNCTION GET_LECS

  SUBROUTINE PRINT_LECS(LECS_IN)
    IMPLICIT NONE
    TYPE(LECS_EFT_PLESS), INTENT(IN) :: LECS_IN
    INTEGER :: I, J
    CHARACTER(LEN=16) :: ORD

    SELECT CASE (LECS_IN%ORDER)
    CASE (0)
      ORD = "LO"
    CASE (1)
      ORD = "NLO"
    CASE (3)
      ORD = "N3LO"
    CASE DEFAULT
      ORD = "UNKNOWN"
    END SELECT

    PRINT *, "LECS_EFT_PLESS:"
    PRINT *, "  ILB   = ", LECS_IN%ILB
    PRINT *, "  ORDER =          ", ORD
    PRINT *, "  RC:"
    DO I = 0, 1
      WRITE(*,'(A,2F12.8)') "    ", LECS_IN%RC(I,0), LECS_IN%RC(I,1)
    END DO
    PRINT *, "  CLO:"
    WRITE(*,'(A,2ES18.8E2)') "    ", LECS_IN%CLO(1), LECS_IN%CLO(0)
    PRINT *, "  CNLO:"
    WRITE(*,'(A,7ES18.8E2)') "    ", (LECS_IN%CNLO(J), J=1,7)
    PRINT *, "  CN3LO:"
    WRITE(*,'(A,7ES18.8E2)') "    ", (LECS_IN%CN3LO(J), J=1,7)
    WRITE(*,'(A,4ES18.8E2)') "    ", (LECS_IN%CN3LO(J), J=8,11)
    PRINT *, "  CIT:"
    WRITE(*,'(A,5ES18.8E2)') "    ", (LECS_IN%CIT(J), J=0,4)
  END SUBROUTINE PRINT_LECS

  SUBROUTINE GET_EFT_RADIAL_FUNCTIONS(R_ARRAY, RC, FUNCTIONS, ORDER_POTENTIAL)
    IMPLICIT NONE
    DOUBLE PRECISION, INTENT(IN) :: RC
    DOUBLE PRECISION, INTENT(IN) :: R_ARRAY(:)
    TYPE(EFT_RADIAL_FUNCTIONS), INTENT(OUT) :: FUNCTIONS
    INTEGER, OPTIONAL, INTENT(IN) :: ORDER_POTENTIAL

    INTEGER :: NR, I, IMAX

    IF (PRESENT(ORDER_POTENTIAL)) THEN
      FUNCTIONS%ORDER = ORDER_POTENTIAL
    ELSE
      FUNCTIONS%ORDER = 3  ! Default to N3LO if not specified
    END IF

    NR = SIZE(R_ARRAY)
    IF (NR < 1) THEN
      PRINT *, "ERROR: No radial points provided for EFT radial functions."
      RETURN
    END IF

    IMAX = 0
    IF (FUNCTIONS%ORDER == 1) THEN
      IMAX = 4
    ELSE
      IMAX = 7
    END IF

    DO I=0, IMAX
      FUNCTIONS%FR_I(I,:) = EFT_RADIAL(I, R_ARRAY, RC)
    END DO
  END SUBROUTINE GET_EFT_RADIAL_FUNCTIONS

  PURE ELEMENTAL FUNCTION EFT_RADIAL(I, R, RC) RESULT(FI)
    IMPLICIT NONE
    INTEGER, INTENT(IN) :: I
    DOUBLE PRECISION, INTENT(IN) :: R, RC
    DOUBLE PRECISION :: FI

    SELECT CASE (I)
    CASE (0)
      FI = 1.d0 ! The CR function for I=0
    CASE (1)
      FI = EFT_RADIAL_1(R, RC)
    CASE (2)
      FI = EFT_RADIAL_2(R, RC)
    CASE (3)
      FI = EFT_RADIAL_3(R, RC)
    CASE (4)
      FI = EFT_RADIAL_4(R, RC)
    CASE (5)
      FI = EFT_RADIAL_5(R, RC)
    CASE (6)
      FI = EFT_RADIAL_6(R, RC)
    CASE (7)
      FI = EFT_RADIAL_7(R, RC)
    CASE DEFAULT
      FI = 0.D0
    END SELECT
    FI = FI * CR(R, RC)
  END FUNCTION EFT_RADIAL

  ! SUBROUTINE COMBINE_POTENTIAL(CHANNEL, FR_MATRIX_EL, LECS_IN, POTENTIAL_OUT)
  !   IMPLICIT NONE
  !   TYPE(SCATTERING_CHANNEL), INTENT(IN) :: CHANNEL
  !   DOUBLE PRECISION, INTENT(IN) :: FR_MATRIX_EL(:,:,:,:)
  !   TYPE(LECS_EFT_PLESS), INTENT(IN) :: LECS_IN
  !   DOUBLE PRECISION :: POTENTIAL_OUT(:,:,:)
  !   INTEGER :: NR, ORDER_, IORDER, N_OPERATORS, NIT_OPERATORS, IOP
  !   INTEGER :: S, T, LS1(2,2), LS2(2,2)

  !   ORDER_ = LECS_IN%ORDER
  !   IF (ORDER_ /= 0 .AND. ORDER_ /= 1 .AND. ORDER_ /= 3) THEN
  !     STOP "ERROR IN COMBINE_POTENTIAL: ORDER must be 0, 1, or 3"
  !   END IF

  !   S = GET_CHANNEL_S(CHANNEL, 1)
  !   T = GET_CHANNEL_T(CHANNEL, 1)

  !   IF ( S==0 .AND. T==0 ) THEN
  !     SELECT CASE (ORDER)
  !     CASE (0)
  !       RETURN
  !     CASE (1)
  !       POTENTIAL_OUT = LECS_IN%CNLO(1) * FR_MATRIX_EL(1,:,:,:) * I2
  !     CASE (3)
  !       POTENTIAL_OUT = LECS_IN%CNLO(1) * FR_MATRIX_EL(1,:,:,:) * I2
  !       POTENTIAL_OUT = POTENTIAL_OUT &
  !                 + LECS_IN%CN3LO(1)  * FR_MATRIX_EL(4,:,:,:) *I2 &
  !                 + LECS_IN%CN3LO(10) * FR_MATRIX_EL(7,:,:,:) *L2_OPERATOR(CHANNEL)
  !     CASE DEFAULT
  !       STOP "ERROR IN EFT_PLESS_PW:: S=0 AND T=0"
  !     END SELECT
  !   ENDIF

  !   IF ( S==1 .AND. T==0 ) THEN
  !     SELECT CASE (ORDER)
  !     CASE (0)
  !       POTENTIAL_OUT = LECS_IN%CLO(T) * FR_MATRIX_EL(1,:,:,:) * I2
  !     CASE (1)
  !       POTENTIAL_OUT = LECS_IN%CLO(T) * FR_MATRIX_EL(1,:,:,:) * I2
  !       POTENTIAL_OUT = POTENTIAL_OUT &
  !                 + LECS_IN%CNLO(2) * FR_MATRIX_EL(2,:,:,:) * I2 &
  !                 + LECS_IN%CNLO(5) * FR_MATRIX_EL(3,:,:,:) * S12_OPERATOR(CHANNEL) &
  !                 + LECS_IN%CNLO(7) * FR_MATRIX_EL(4,:,:,:) * LS_OPERATOR(CHANNEL)
  !     CASE (3)
  !       LS1 = LS_OPERATOR(CHANNEL)
  !       LS2 = MATMUL(LS1, LS1)
  !       POTENTIAL_OUT = LECS_IN%CLO(T) * FR_MATRIX_EL(1,:,:,:) * I2
  !       POTENTIAL_OUT = POTENTIAL_OUT &
  !                 + LECS_IN%CNLO(2) * FR_MATRIX_EL(2,:,:,:) * I2 &
  !                 + LECS_IN%CNLO(5) * FR_MATRIX_EL(3,:,:,:) * S12_OPERATOR(CHANNEL) &
  !                 + LECS_IN%CNLO(7) * FR_MATRIX_EL(4,:,:,:) * LS_OPERATOR(CHANNEL)
  !       POTENTIAL_OUT = POTENTIAL_OUT &
  !                 + LECS_IN%CN3LO(2) * FR_MATRIX_EL(5,:,:,:) * I2 &
  !                 + LECS_IN%CN3LO(5) * FR_MATRIX_EL(6,:,:,:) * S12_OPERATOR(CHANNEL) &
  !                 + LECS_IN%CN3LO(7) * FR_MATRIX_EL(7,:,:,:) * LS_OPERATOR(CHANNEL) &
  !                 + LECS_IN%CN3LO(9) * FR_MATRIX_EL(8,:,:,:) * LS2 &
  !                 + LECS_IN%CN3LO(11)* FR_MATRIX_EL(8,:,:,:) * L2_OPERATOR(CHANNEL)
  !     CASE DEFAULT
  !       STOP "ERROR IN EFT_PLESS_PW:: S=1 AND T=0"
  !     END SELECT
  !   ENDIF

  !   IF ( S==0 .AND. T==1 ) THEN
  !     SELECT CASE (ORDER)
  !     CASE (0)
  !       POTENTIAL_OUT = LECS_IN%CLO(T) * FR_MATRIX_EL(1,:,:,:) * I2
  !     CASE (1)
  !       POTENTIAL_OUT = LECS_IN%CLO(T) * FR_MATRIX_EL(1,:,:,:) * I2
  !       POTENTIAL_OUT = POTENTIAL_OUT &
  !                 + LECS_IN%CNLO(3)    * FR_MATRIX_EL(2,:,:,:) * I2 &
  !                 + LECS_IN%CIT(0)     * FR_MATRIX_EL(1,:,:,:) * T12_OPERATOR(CHANNEL) * I2
  !     CASE (3)
  !       POTENTIAL_OUT = LECS_IN%CLO(T) * FR_MATRIX_EL(1,:,:,:) * I2
  !       POTENTIAL_OUT = POTENTIAL_OUT &
  !                 + LECS_IN%CNLO(3)     * FR_MATRIX_EL(2,:,:,:) * I2 &
  !                 + LECS_IN%CIT(0)      * FR_MATRIX_EL(1,:,:,:) * T12_OPERATOR(CHANNEL) * I2
  !       POTENTIAL_OUT = POTENTIAL_OUT &
  !                 + LECS_IN%CN3LO(3) * FR_MATRIX_EL(5,:,:,:)     * I2 &
  !                 + LECS_IN%CN3LO(10)* FR_MATRIX_EL(8,:,:,:)     * L2_OPERATOR(CHANNEL) &
  !                 + LECS_IN%CIT(1)   * FR_MATRIX_EL(2,:,:,:)     * T12_OPERATOR(CHANNEL) * I2
  !     CASE DEFAULT
  !       STOP "ERROR IN EFT_PLESS_PW:: S=0 AND T=1"
  !     END SELECT
  !   ENDIF

  !   IF ( S==1 .AND. T==1 ) THEN
  !     SELECT CASE (ORDER)
  !     CASE (0)
  !       RETURN
  !     CASE (1)
  !       POTENTIAL_OUT = LECS_IN%CNLO(4) * FR_MATRIX_EL(2,:,:,:) *  I2 &
  !             + LECS_IN%CNLO(6)         * FR_MATRIX_EL(3,:,:,:) *  S12_OPERATOR(CHANNEL) &
  !             + LECS_IN%CNLO(7)         * FR_MATRIX_EL(4,:,:,:) *  LS_OPERATOR(CHANNEL) &
  !             + LECS_IN%CIT(0)          * FR_MATRIX_EL(1,:,:,:) *  T12_OPERATOR(CHANNEL) * I2
  !     CASE (3)
  !       LS1 = LS_OPERATOR(CHANNEL)
  !       LS2 = MATMUL(LS1, LS1)
  !       POTENTIAL_OUT = LECS_IN%CNLO(4) * FR_MATRIX_EL(2,:,:,:) *  I2 &
  !             + LECS_IN%CNLO(6)         * FR_MATRIX_EL(3,:,:,:) *  S12_OPERATOR(CHANNEL) &
  !             + LECS_IN%CNLO(7)         * FR_MATRIX_EL(4,:,:,:) *  LS_OPERATOR(CHANNEL) &
  !             + LECS_IN%CIT(0)          * FR_MATRIX_EL(1,:,:,:) *  T12_OPERATOR(CHANNEL) * I2
  !       POTENTIAL_OUT =   POTENTIAL_OUT &
  !             + LECS_IN%CN3LO(4) * FR_MATRIX_EL(5,:,:,:)    * I2 &
  !             + LECS_IN%CN3LO(6) * FR_MATRIX_EL(6,:,:,:)    * S12_OPERATOR(CHANNEL) &
  !             + LECS_IN%CN3LO(8) * FR_MATRIX_EL(7,:,:,:)    * LS_OPERATOR(CHANNEL) &
  !             + LECS_IN%CN3LO(9) * FR_MATRIX_EL(8,:,:,:)    * LS2 &
  !             + LECS_IN%CN3LO(11)* FR_MATRIX_EL(8,:,:,:)    * L2_OPERATOR(CHANNEL) &
  !             +(  LECS_IN%CIT(2) * FR_MATRIX_EL(2,:,:,:)    * I2  + &
  !                 LECS_IN%CIT(3) * FR_MATRIX_EL(3,:,:,:)    * S12_OPERATOR(CHANNEL) + &
  !                 LECS_IN%CIT(4) * FR_MATRIX_EL(4,:,:,:)    * LS_OPERATOR(CHANNEL) &
  !                                                       ) * T12_OPERATOR(CHANNEL)
  !     CASE DEFAULT
  !       STOP "ERROR IN EFT_PLESS_PW:: S=1 AND T=1"
  !     END SELECT
  !   ENDIF
  ! END SUBROUTINE COMBINE_POTENTIAL

END MODULE EFT_PLESS

