MODULE REALLOCATE_UTILS
  IMPLICIT NONE
  PRIVATE

  PUBLIC :: REALLOCATE_1D_1_INT
  PUBLIC :: REALLOCATE_1D_1, REALLOCATE_1D_2, REALLOCATE_1D_3, REALLOCATE_1D_4, REALLOCATE_1D_5
  PUBLIC :: REALLOCATE_1D_6, REALLOCATE_1D_7, REALLOCATE_1D_8, REALLOCATE_1D_9, REALLOCATE_1D_10
  PUBLIC :: REALLOCATE_2D_1, REALLOCATE_2D_2, REALLOCATE_2D_3, REALLOCATE_2D_4, REALLOCATE_2D_5
  PUBLIC :: REALLOCATE_2D_6, REALLOCATE_2D_7, REALLOCATE_2D_8, REALLOCATE_2D_9, REALLOCATE_2D_10
  PUBLIC :: REALLOCATE_3D_1

CONTAINS

! -------- 1D --------
SUBROUTINE REALLOCATE_1D_1(A1, N)
  DOUBLE PRECISION, ALLOCATABLE, INTENT(INOUT) :: A1(:)
  INTEGER, INTENT(IN) :: N
  IF (.NOT. ALLOCATED(A1)) THEN
    ALLOCATE(A1(N))
  ELSEIF (SIZE(A1) .NE. N) THEN
    DEALLOCATE(A1)
    ALLOCATE(A1(N))
  END IF
END SUBROUTINE

SUBROUTINE REALLOCATE_1D_1_INT(A1, N)
  INTEGER, ALLOCATABLE, INTENT(INOUT) :: A1(:)
  INTEGER, INTENT(IN) :: N
  IF (.NOT. ALLOCATED(A1)) THEN
    ALLOCATE(A1(N))
  ELSEIF (SIZE(A1) .NE. N) THEN
    DEALLOCATE(A1)
    ALLOCATE(A1(N))
  END IF
END SUBROUTINE

SUBROUTINE REALLOCATE_1D_2(A1, A2, N)
  DOUBLE PRECISION, ALLOCATABLE, INTENT(INOUT) :: A1(:), A2(:)
  INTEGER, INTENT(IN) :: N
  CALL REALLOCATE_1D_1(A1, N)
  CALL REALLOCATE_1D_1(A2, N)
END SUBROUTINE

SUBROUTINE REALLOCATE_1D_3(A1, A2, A3, N)
  DOUBLE PRECISION, ALLOCATABLE, INTENT(INOUT) :: A1(:), A2(:), A3(:)
  INTEGER, INTENT(IN) :: N
  CALL REALLOCATE_1D_1(A1, N)
  CALL REALLOCATE_1D_1(A2, N)
  CALL REALLOCATE_1D_1(A3, N)
END SUBROUTINE

SUBROUTINE REALLOCATE_1D_4(A1, A2, A3, A4, N)
  DOUBLE PRECISION, ALLOCATABLE, INTENT(INOUT) :: A1(:), A2(:), A3(:), A4(:)
  INTEGER, INTENT(IN) :: N
  CALL REALLOCATE_1D_1(A1, N)
  CALL REALLOCATE_1D_1(A2, N)
  CALL REALLOCATE_1D_1(A3, N)
  CALL REALLOCATE_1D_1(A4, N)
END SUBROUTINE

SUBROUTINE REALLOCATE_1D_5(A1, A2, A3, A4, A5, N)
  DOUBLE PRECISION, ALLOCATABLE, INTENT(INOUT) :: A1(:), A2(:), A3(:), A4(:), A5(:)
  INTEGER, INTENT(IN) :: N
  CALL REALLOCATE_1D_1(A1, N)
  CALL REALLOCATE_1D_1(A2, N)
  CALL REALLOCATE_1D_1(A3, N)
  CALL REALLOCATE_1D_1(A4, N)
  CALL REALLOCATE_1D_1(A5, N)
END SUBROUTINE

SUBROUTINE REALLOCATE_1D_6(A1, A2, A3, A4, A5, A6, N)
  DOUBLE PRECISION, ALLOCATABLE, INTENT(INOUT) :: A1(:), A2(:), A3(:), A4(:), A5(:), A6(:)
  INTEGER, INTENT(IN) :: N
  CALL REALLOCATE_1D_1(A1, N)
  CALL REALLOCATE_1D_1(A2, N)
  CALL REALLOCATE_1D_1(A3, N)
  CALL REALLOCATE_1D_1(A4, N)
  CALL REALLOCATE_1D_1(A5, N)
  CALL REALLOCATE_1D_1(A6, N)
END SUBROUTINE

SUBROUTINE REALLOCATE_1D_7(A1, A2, A3, A4, A5, A6, A7, N)
  DOUBLE PRECISION, ALLOCATABLE, INTENT(INOUT) :: A1(:), A2(:), A3(:), A4(:), A5(:), A6(:), A7(:)
  INTEGER, INTENT(IN) :: N
  CALL REALLOCATE_1D_1(A1, N)
  CALL REALLOCATE_1D_1(A2, N)
  CALL REALLOCATE_1D_1(A3, N)
  CALL REALLOCATE_1D_1(A4, N)
  CALL REALLOCATE_1D_1(A5, N)
  CALL REALLOCATE_1D_1(A6, N)
  CALL REALLOCATE_1D_1(A7, N)
END SUBROUTINE

SUBROUTINE REALLOCATE_1D_8(A1, A2, A3, A4, A5, A6, A7, A8, N)
  DOUBLE PRECISION, ALLOCATABLE, INTENT(INOUT) :: A1(:), A2(:), A3(:), A4(:), A5(:), A6(:), A7(:), A8(:)
  INTEGER, INTENT(IN) :: N
  CALL REALLOCATE_1D_1(A1, N)
  CALL REALLOCATE_1D_1(A2, N)
  CALL REALLOCATE_1D_1(A3, N)
  CALL REALLOCATE_1D_1(A4, N)
  CALL REALLOCATE_1D_1(A5, N)
  CALL REALLOCATE_1D_1(A6, N)
  CALL REALLOCATE_1D_1(A7, N)
  CALL REALLOCATE_1D_1(A8, N)
END SUBROUTINE

SUBROUTINE REALLOCATE_1D_9(A1, A2, A3, A4, A5, A6, A7, A8, A9, N)
  DOUBLE PRECISION, ALLOCATABLE, INTENT(INOUT) :: A1(:), A2(:), A3(:), A4(:), A5(:), A6(:), A7(:), A8(:), A9(:)
  INTEGER, INTENT(IN) :: N
  CALL REALLOCATE_1D_1(A1, N)
  CALL REALLOCATE_1D_1(A2, N)
  CALL REALLOCATE_1D_1(A3, N)
  CALL REALLOCATE_1D_1(A4, N)
  CALL REALLOCATE_1D_1(A5, N)
  CALL REALLOCATE_1D_1(A6, N)
  CALL REALLOCATE_1D_1(A7, N)
  CALL REALLOCATE_1D_1(A8, N)
  CALL REALLOCATE_1D_1(A9, N)
END SUBROUTINE

SUBROUTINE REALLOCATE_1D_10(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, N)
  DOUBLE PRECISION, ALLOCATABLE, INTENT(INOUT) :: A1(:), A2(:), A3(:), A4(:), A5(:), A6(:), A7(:), A8(:), A9(:), A10(:)
  INTEGER, INTENT(IN) :: N
  CALL REALLOCATE_1D_1(A1, N)
  CALL REALLOCATE_1D_1(A2, N)
  CALL REALLOCATE_1D_1(A3, N)
  CALL REALLOCATE_1D_1(A4, N)
  CALL REALLOCATE_1D_1(A5, N)
  CALL REALLOCATE_1D_1(A6, N)
  CALL REALLOCATE_1D_1(A7, N)
  CALL REALLOCATE_1D_1(A8, N)
  CALL REALLOCATE_1D_1(A9, N)
  CALL REALLOCATE_1D_1(A10, N)
END SUBROUTINE

! -------- 2D --------
SUBROUTINE REALLOCATE_2D_1(A1, N1, N2)
  DOUBLE PRECISION, ALLOCATABLE, INTENT(INOUT) :: A1(:,:)
  INTEGER, INTENT(IN) :: N1, N2
  IF (.NOT. ALLOCATED(A1) .OR. ANY(SHAPE(A1) /= [N1, N2])) THEN
    IF (ALLOCATED(A1)) DEALLOCATE(A1)
    ALLOCATE(A1(N1, N2))
  END IF
END SUBROUTINE

SUBROUTINE REALLOCATE_2D_2(A1, A2, N1, N2)
  DOUBLE PRECISION, ALLOCATABLE, INTENT(INOUT) :: A1(:,:), A2(:,:)
  INTEGER, INTENT(IN) :: N1, N2
  CALL REALLOCATE_2D_1(A1, N1, N2)
  CALL REALLOCATE_2D_1(A2, N1, N2)
END SUBROUTINE

SUBROUTINE REALLOCATE_2D_3(A1, A2, A3, N1, N2)
  DOUBLE PRECISION, ALLOCATABLE, INTENT(INOUT) :: A1(:,:), A2(:,:), A3(:,:)
  INTEGER, INTENT(IN) :: N1, N2
  CALL REALLOCATE_2D_1(A1, N1, N2)
  CALL REALLOCATE_2D_1(A2, N1, N2)
  CALL REALLOCATE_2D_1(A3, N1, N2)
END SUBROUTINE

SUBROUTINE REALLOCATE_2D_4(A1, A2, A3, A4, N1, N2)
  DOUBLE PRECISION, ALLOCATABLE, INTENT(INOUT) :: A1(:,:), A2(:,:), A3(:,:), A4(:,:)
  INTEGER, INTENT(IN) :: N1, N2
  CALL REALLOCATE_2D_1(A1, N1, N2)
  CALL REALLOCATE_2D_1(A2, N1, N2)
  CALL REALLOCATE_2D_1(A3, N1, N2)
  CALL REALLOCATE_2D_1(A4, N1, N2)
END SUBROUTINE

SUBROUTINE REALLOCATE_2D_5(A1, A2, A3, A4, A5, N1, N2)
  DOUBLE PRECISION, ALLOCATABLE, INTENT(INOUT) :: A1(:,:), A2(:,:), A3(:,:), A4(:,:), A5(:,:)
  INTEGER, INTENT(IN) :: N1, N2
  CALL REALLOCATE_2D_1(A1, N1, N2)
  CALL REALLOCATE_2D_1(A2, N1, N2)
  CALL REALLOCATE_2D_1(A3, N1, N2)
  CALL REALLOCATE_2D_1(A4, N1, N2)
  CALL REALLOCATE_2D_1(A5, N1, N2)
END SUBROUTINE

SUBROUTINE REALLOCATE_2D_6(A1, A2, A3, A4, A5, A6, N1, N2)
  DOUBLE PRECISION, ALLOCATABLE, INTENT(INOUT) :: A1(:,:), A2(:,:), A3(:,:), A4(:,:), A5(:,:), A6(:,:)
  INTEGER, INTENT(IN) :: N1, N2
  CALL REALLOCATE_2D_1(A1, N1, N2)
  CALL REALLOCATE_2D_1(A2, N1, N2)
  CALL REALLOCATE_2D_1(A3, N1, N2)
  CALL REALLOCATE_2D_1(A4, N1, N2)
  CALL REALLOCATE_2D_1(A5, N1, N2)
  CALL REALLOCATE_2D_1(A6, N1, N2)
END SUBROUTINE

SUBROUTINE REALLOCATE_2D_7(A1, A2, A3, A4, A5, A6, A7, N1, N2)
  DOUBLE PRECISION, ALLOCATABLE, INTENT(INOUT) :: A1(:,:), A2(:,:), A3(:,:), A4(:,:), A5(:,:), A6(:,:), A7(:,:)
  INTEGER, INTENT(IN) :: N1, N2
  CALL REALLOCATE_2D_1(A1, N1, N2)
  CALL REALLOCATE_2D_1(A2, N1, N2)
  CALL REALLOCATE_2D_1(A3, N1, N2)
  CALL REALLOCATE_2D_1(A4, N1, N2)
  CALL REALLOCATE_2D_1(A5, N1, N2)
  CALL REALLOCATE_2D_1(A6, N1, N2)
  CALL REALLOCATE_2D_1(A7, N1, N2)
END SUBROUTINE

SUBROUTINE REALLOCATE_2D_8(A1, A2, A3, A4, A5, A6, A7, A8, N1, N2)
  DOUBLE PRECISION, ALLOCATABLE, INTENT(INOUT) :: A1(:,:), A2(:,:), A3(:,:), A4(:,:), A5(:,:), A6(:,:), A7(:,:), A8(:,:)
  INTEGER, INTENT(IN) :: N1, N2
  CALL REALLOCATE_2D_1(A1, N1, N2)
  CALL REALLOCATE_2D_1(A2, N1, N2)
  CALL REALLOCATE_2D_1(A3, N1, N2)
  CALL REALLOCATE_2D_1(A4, N1, N2)
  CALL REALLOCATE_2D_1(A5, N1, N2)
  CALL REALLOCATE_2D_1(A6, N1, N2)
  CALL REALLOCATE_2D_1(A7, N1, N2)
  CALL REALLOCATE_2D_1(A8, N1, N2)
END SUBROUTINE

SUBROUTINE REALLOCATE_2D_9(A1, A2, A3, A4, A5, A6, A7, A8, A9, N1, N2)
  DOUBLE PRECISION, ALLOCATABLE, INTENT(INOUT) :: A1(:,:), A2(:,:), A3(:,:), A4(:,:), A5(:,:), A6(:,:), A7(:,:), A8(:,:), A9(:,:)
  INTEGER, INTENT(IN) :: N1, N2
  CALL REALLOCATE_2D_1(A1, N1, N2)
  CALL REALLOCATE_2D_1(A2, N1, N2)
  CALL REALLOCATE_2D_1(A3, N1, N2)
  CALL REALLOCATE_2D_1(A4, N1, N2)
  CALL REALLOCATE_2D_1(A5, N1, N2)
  CALL REALLOCATE_2D_1(A6, N1, N2)
  CALL REALLOCATE_2D_1(A7, N1, N2)
  CALL REALLOCATE_2D_1(A8, N1, N2)
  CALL REALLOCATE_2D_1(A9, N1, N2)
END SUBROUTINE

SUBROUTINE REALLOCATE_2D_10(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, N1, N2)
  DOUBLE PRECISION, ALLOCATABLE, INTENT(INOUT) :: A1(:,:), A2(:,:), A3(:,:), A4(:,:), A5(:,:), &
                                                  A6(:,:), A7(:,:), A8(:,:), A9(:,:), A10(:,:)
  INTEGER, INTENT(IN) :: N1, N2
  CALL REALLOCATE_2D_1(A1, N1, N2)
  CALL REALLOCATE_2D_1(A2, N1, N2)
  CALL REALLOCATE_2D_1(A3, N1, N2)
  CALL REALLOCATE_2D_1(A4, N1, N2)
  CALL REALLOCATE_2D_1(A5, N1, N2)
  CALL REALLOCATE_2D_1(A6, N1, N2)
  CALL REALLOCATE_2D_1(A7, N1, N2)
  CALL REALLOCATE_2D_1(A8, N1, N2)
  CALL REALLOCATE_2D_1(A9, N1, N2)
  CALL REALLOCATE_2D_1(A10, N1, N2)
END SUBROUTINE

! -------- 3D --------
SUBROUTINE REALLOCATE_3D_1(A1, N1, N2, N3)
  DOUBLE PRECISION, ALLOCATABLE, INTENT(INOUT) :: A1(:,:,:)
  INTEGER, INTENT(IN) :: N1, N2, N3
  IF (.NOT. ALLOCATED(A1) .OR. ANY(SHAPE(A1) /= [N1, N2, N3])) THEN
    IF (ALLOCATED(A1)) DEALLOCATE(A1)
    ALLOCATE(A1(N1, N2, N3))
  END IF
END SUBROUTINE

END MODULE REALLOCATE_UTILS