MODULE POTENTIALS
  IMPLICIT NONE
  PUBLIC :: POT_PW
CONTAINS
  SUBROUTINE POT_PW(IPOT, ILB, LEMP, L, S, J, T1Z, T2Z, R, VPW)
    USE AV18
    USE AV14
    USE EFT_PLESS
    IMPLICIT NONE
    INTEGER, INTENT(IN) :: IPOT, LEMP, L, S, J, T1Z, T2Z
    DOUBLE PRECISION, INTENT(IN) :: R
    DOUBLE PRECISION, INTENT(OUT):: VPW(2,2)
    INTEGER, INTENT(IN) :: ILB
  !
    INTEGER :: T
  !
    T = MOD( MOD(L+S,2) + 1 , 2)
  !
    SELECT CASE (IPOT)
    CASE (14)
      CALL AV14PW(LEMP, L, S, J, T1Z, T2Z, R, VPW)
      RETURN
    CASE (18)
      ! CALL AV18PW(ILB, L, S, J, T, T1Z, T2Z, R, VPW, LEMP)
      RETURN
    CASE (19)
      ! CALL EFT_PLESS_PW(LEMP, ILB, L, S, J, T1Z, T2Z, R, VPW)
      STOP "POT_PW: EFT_PLESS_PW not implemented"
      RETURN
    CASE (21)
      CALL EFT_PLESS_PW_FITTED(ILB, R, L, S, J, T1Z + T2Z, VPW)
    CASE DEFAULT
      STOP "ERROR, POTENTIAL NOT FOUND"
    END SELECT
    RETURN

  END SUBROUTINE POT_PW
END MODULE POTENTIALS