SUBROUTINE NN_SCATTERING_VARIATIONAL(E, J, L, S, TZ, IPOT, ILB, LEMP, VCOUL)
  IMPLICIT NONE
  ! INPUT PARAMETERS
  DOUBLE PRECISION, INTENT(IN) :: E
  INTEGER, INTENT(IN) :: J, L, S, TZ, IPOT, ILB, LEMP
  LOGICAL, INTENT(IN) :: VCOUL

  ! DECLARE CONSTANTS AS PARAMETERS
  DOUBLE PRECISION, PARAMETER :: HC = 197.327053D0
  DOUBLE PRECISION, PARAMETER :: MP = 938.272029D0
  DOUBLE PRECISION, PARAMETER :: MN = 939.565630D0
  DOUBLE PRECISION, PARAMETER :: MR = MP * MN / (MP + MN)
  DOUBLE PRECISION, PARAMETER :: PI = 4*DATAN(1.0D0)
  COMPLEX*16, PARAMETER ::       IM = (0.0D0, 1.0D0)
  DOUBLE PRECISION, PARAMETER :: ONE = 1.0D0, ZERO = 0.0D0

  INTEGER, PARAMETER :: NCH_MAX = 2

! VARIABLES AND PARAMETERS FOR DGESV
  INTEGER, PARAMETER :: NNE = 80, NNN = NNE*NCH_MAX
  DOUBLE PRECISION, DIMENSION(NNN, NNN) :: C, CC, CCC
  DOUBLE PRECISION, DIMENSION(NNN, NNN) :: CAR, CARR, CAI, CAII
  DOUBLE PRECISION, DIMENSION(NCH_MAX, NNN) :: XRCOEFF, XICOEFF
  DOUBLE PRECISION, DIMENSION(NNN, NNN) :: IPIV
  INTEGER :: NDIM ! GIVEN BY CORE_CORE_MATRIX_ELEMENTS
  INTEGER :: INFO
  
  ! THE SUBROUTINE DOES NOT MODIFY THE CONSTANTS, AS THEY ARE PARAMETERS
  ! ADDITIONAL LOGIC CAN BE ADDED HERE IF NEEDED
  DOUBLE PRECISION :: K, HTM, M
  INTEGER :: T
  INTEGER :: LC(NCH_MAX), NCH

  ! Initialize HTM
  SELECT CASE (TZ)
    CASE (1)
      M = MP
    CASE (0)
      M = MP * MN / (MP + MN)
    CASE (-1)
      M = MN
    CASE DEFAULT
      PRINT *, "Invalid TZ value"
      STOP
  END SELECT

  HTM = HC**2 / (2 * M)

  ! Ensure T is set such that T + L + S is odd
  IF (MOD(L + S, 2) == 0) THEN
    T = 1
  ELSE
    T = 0
  END IF

  K = DSQRT(2*E*MR) / HC

  PRINT 5
  PRINT 15, "L", "S", "T", "TZ", "J"
  PRINT 5
  LC(1) = L
  NCH = 1
  PRINT 20, LC(1), S, T, TZ, J
  IF (J-L.EQ.1) THEN 
    LC(2) = L + 2
    PRINT 20, LC(2), S, T, TZ, J
    NCH = 2
  ENDIF
  PRINT 5

  PRINT *, "E:    ", E, " MeV"
  PRINT *, "HTM:  ", HTM, " MeV fm^2"
  PRINT *, "k:    ", K, " fm^-1"
  PRINT 10, "J:     ", J
  PRINT 10, "NCH:   ", NCH
  PRINT 10, "L0:    ", LC(1)
  IF (NCH.EQ.2) PRINT 10, "L1:    ", LC(2)
  PRINT 10, "S:     ", S
  PRINT 10, "T:     ", T
  PRINT 10, "TZ:    ", TZ

! Evaluating the matrix elements
  CALL CORE_CORE_MATRIX_ELEMENTS            (LC, S, T, TZ, J, K, E, NCH, VCOUL, IPOT, ILB, LEMP)
  CALL ASYMPTOTIC_CORE_MATRIX_ELEMENTS      (LC, S, T, TZ, J, K, E, NCH, VCOUL, IPOT, ILB, LEMP)
  CALL ASYMPTOTIC_ASYMPTOTIC_MATRIX_ELEMENTS(LC, S, T, TZ, J, K, E, NCH, VCOUL, IPOT, ILB, LEMP)

! Preparing the matrix elements for the diagonalization


! Solving the eigenvalue problem using LAPACK dgesv
! Evaluating for the "c_{n, alpha}" coefficients
  CALL DGESV() 

! Evaluating the "R_{alpha, beta}" matrix elements
  CALL DGESV()


! Evaluating the "R_{alpha, beta}" matrix elements to the second order



! Calculating the phase shifts and mixing angles






  5 FORMAT(30("-"))
 10 FORMAT(" ",A, I2)
 15 FORMAT(" ", A5, A5, A5, A5, A5, A5)
 20 FORMAT(" ", I5, I5, I5, I5, I5, I5)

END SUBROUTINE NN_SCATTERING_VARIATIONAL



SUBROUTINE CORE_CORE_MATRIX_ELEMENTS(LV, S, T, TZ, J, K, E, NCH, VCOUL, IPOT, ILB, LEMP)
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: LV(NCH), S, T, TZ, J, NCH, IPOT, ILB, LEMP
  DOUBLE PRECISION, INTENT(IN) :: K, E
  LOGICAL, INTENT(IN) :: VCOUL

  ! Add the implementation of the core-core matrix elements here

END SUBROUTINE CORE_CORE_MATRIX_ELEMENTS

SUBROUTINE ASYMPTOTIC_CORE_MATRIX_ELEMENTS(LV, S, T, TZ, J, K, E, NCH, VCOUL, IPOT, ILB, LEMP)
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: LV(NCH), S, T, TZ, J, NCH, IPOT, ILB, LEMP
  DOUBLE PRECISION, INTENT(IN) :: K, E
  LOGICAL, INTENT(IN) :: VCOUL

  ! Add the implementation of the asymptotic core matrix elements here

END SUBROUTINE ASYMPTOTIC_CORE_MATRIX_ELEMENTS

SUBROUTINE ASYMPTOTIC_ASYMPTOTIC_MATRIX_ELEMENTS(LV, S, T, TZ, J, K, E, NCH, VCOUL, IPOT, ILB, LEMP)
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: LV(NCH), S, T, TZ, J, NCH, IPOT, ILB, LEMP
  DOUBLE PRECISION, INTENT(IN) :: K, E
  LOGICAL, INTENT(IN) :: VCOUL

  ! Add the implementation of the asymptotic-asymptotic matrix elements here

END SUBROUTINE ASYMPTOTIC_ASYMPTOTIC_MATRIX_ELEMENTS