FUNCTION TRIANGLE_LSJ(J, S, L) RESULT(ISVALID)
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: J, S, L
  LOGICAL :: ISVALID

  ISVALID = (ABS(J - S) <= L) .AND. (L <= (J + S))
END FUNCTION TRIANGLE_LSJ

FUNCTION CHECK_QUANTUM_NUMBERS(J, L, S, TZ) RESULT(ISVALID)
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: J, L, S, TZ
  INTEGER :: T
  LOGICAL :: ISVALID
  LOGICAL, EXTERNAL :: TRIANGLE_LSJ

  ! Ensure T is set such that T + L + S is odd
  IF (MOD(L + S, 2) == 0) THEN
    T = 1
  ELSE
    T = 0
  END IF

  ISVALID = (J >= 0.0) .AND. (L >= 0.0) .AND. (S >= 0.0) .AND. &
            (T >= 0.0) .AND. (ABS(TZ) <= T) .AND. &
            TRIANGLE_LSJ(J, S, L)
END FUNCTION CHECK_QUANTUM_NUMBERS