PROGRAM SCATTERING_NN_ZERO_ENERGY
  USE SCATTERING_NN_VARIATIONAL
  USE QUANTUM_NUMBERS
  IMPLICIT NONE
  INTEGER, PARAMETER :: NCHANNELS = 3
  TYPE(SCATTERING_CHANNEL) :: CHANNELS(NCHANNELS)
  TYPE(PHASE_SHIFT_RESULT) :: PS(NCHANNELS,1)
  DOUBLE PRECISION :: ENERGIES(1)
  INTEGER :: IPOT, ILB, LEMP=0

  IPOT = 18
  ILB = 1

  ENERGIES(1) = 0.0D0
  CALL SET_CHANNEL(CHANNELS(1), 0, 0, 0, 0)
  CALL SET_CHANNEL(CHANNELS(2), 1, 0, 1, 0)
  CALL SET_CHANNEL(CHANNELS(3), 1, 1, 0, 0)
  
  CALL SET_ENERGIES(ENERGIES)
  CALL SET_CHANNELS(CHANNELS)
  
  CALL NN_SCATTERING_VARIATIONAL_ENERGIES_CHANNELS(ENERGIES, CHANNELS, LEMP, PS, IPOT=IPOT, ILB=ILB)
  
  WRITE(*,*)
  WRITE(*,*) "Scattering phase shifts at zero energy for channel: ", GET_CHANNEL_NAME(CHANNELS(1))
  WRITE(*,*) "R(0,0)", PS(1,1)%R(1,1)
  WRITE(*,*) "R(0,1)", PS(1,1)%R(1,2)
  WRITE(*,*) "R(1,0)", PS(1,1)%R(2,1)
  WRITE(*,*) "R(1,1)", PS(1,1)%R(2,2)

  WRITE(*,*)
  WRITE(*,*) "Scattering phase shifts at zero energy for channel: ", GET_CHANNEL_NAME(CHANNELS(2))
  WRITE(*,*) "R(0,0)", PS(2,1)%R(1,1)
  WRITE(*,*) "R(0,1)", PS(2,1)%R(1,2)
  WRITE(*,*) "R(1,0)", PS(2,1)%R(2,1)
  WRITE(*,*) "R(1,1)", PS(2,1)%R(2,2)

  WRITE(*,*)
  WRITE(*,*) "Scattering phase shifts at zero energy for channel: ", GET_CHANNEL_NAME(CHANNELS(3))
  WRITE(*,*) "R(0,0)", PS(3,1)%R(1,1)
  WRITE(*,*) "R(0,1)", PS(3,1)%R(1,2)
  WRITE(*,*) "R(1,0)", PS(3,1)%R(2,1)
  WRITE(*,*) "R(1,1)", PS(3,1)%R(2,2)

END PROGRAM SCATTERING_NN_ZERO_ENERGY