PROGRAM PRINT_FITTED_POTENTIAL
  USE EFT_PLESS
  USE QUANTUM_NUMBERS
  IMPLICIT NONE

  INTEGER, PARAMETER :: LEMP = 0
  TYPE(SCATTERING_CHANNEL), ALLOCATABLE :: CHANNELS(:)
  TYPE(SCATTERING_CHANNEL) :: CHANNEL
  DOUBLE PRECISION :: R, VPW(2,2)
  INTEGER :: TZ, ICH, IR
  INTEGER :: L, S, J, T1Z, T2Z

  DO TZ = -1, 1
    CALL PREPARE_CHANNELS(2, 2, TZ, CHANNELS)
    CALL TZ_TO_T1Z_T2Z(TZ, T1Z, T2Z)
    DO ICH = 1, SIZE(CHANNELS)
      CHANNEL = CHANNELS(ICH)
      L = CHANNEL%L()
      S = CHANNEL%S()
      J = CHANNEL%J()
      DO IR = 1, 1000
        R = IR * 0.01D0
        CALL EFT_PLESS_PW_FITTED(1, L, S, J, T1Z, T2Z, R, VPW, LEMP)
        WRITE((2-TZ)*1000 + (2*S+1)*100 + L*10 + J, *) R, VPW(1,1), VPW(2,2), VPW(1,2), VPW(2,1)
      ENDDO
    ENDDO
  ENDDO

END PROGRAM PRINT_FITTED_POTENTIAL