PROGRAM MAIN_SCATTERING_ZERO_ENERGY_R0
  USE SCATTERING_NN_VARIATIONAL
  USE QUANTUM_NUMBERS
  USE SCATTERING
  USE LOG, ONLY: LOG_OBJ => LOGGER
  USE strings_utils
  IMPLICIT NONE
  
  DOUBLE PRECISION, PARAMETER :: K_SMALL = 1.d-8
  DOUBLE PRECISION, PARAMETER :: PI = 4.D0*DATAN(1.D0)
  TYPE(LOG_OBJ) :: LOGGER
  CHARACTER(LEN=1024) :: MESSAGE
  INTEGER, PARAMETER :: LMAX = 0, JMAX = 0, TZ = 0
  INTEGER, PARAMETER :: LEMP = 0, IPOT =18, ILB = 1
  TYPE(SCATTERING_CHANNEL) :: CHANNELS(1)
  TYPE(PHASE_SHIFT_RESULT) :: PS(1,3)
  DOUBLE PRECISION :: ENERGY(1) = 0.0D0
  INTEGER :: NCHANNELS
  DOUBLE PRECISION RBB1(2,2), RBB2(2,2), K2, HTM, r0(2), E
  INTEGER :: L, S, J
  INTEGER, EXTERNAL :: DOUBLE_FACTORIAL

  ! Read E from first argument if provided
  IF (COMMAND_ARGUMENT_COUNT() >= 1) THEN
    CALL GET_COMMAND_ARGUMENT(1, MESSAGE)
    READ(MESSAGE, *) E
  ELSE
    STOP "No energy provided. Please provide an energy value as the first argument."
  END IF

  CALL LOGGER%SET_LOG_MAX_LEVEL(3)

  L = 2
  S = 0
  J = 2
  CALL SET_CHANNEL(CHANNELS(1), J, L, S, TZ)
  CALL CHANNELS(1)%TO_STRING(MESSAGE)
  CALL LOGGER%LOG_DEBUG(TRIM(MESSAGE))


  CALL NN_SCATTERING_VARIATIONAL_ENERGIES_CHANNELS(ENERGY, CHANNELS, LEMP, PS, IPOT=IPOT, ILB=ILB)
  CALL LOGGER%LOG_INFO("Energy: " // TRIM(TO_STRING(ENERGY(1))))
  CALL LOGGER%LOG_INFO("R11: " // TRIM(TO_STRING(PS(1,1)%R_BB(1,1))))
  CALL LOGGER%LOG_INFO("R12: " // TRIM(TO_STRING(PS(1,1)%R_BB(2,1))))
  CALL LOGGER%LOG_INFO("R22: " // TRIM(TO_STRING(PS(1,1)%R_BB(2,2))))
  RBB1 = PS(1,1)%R_BB
  HTM = GET_HTM()
  CALL RESET_SCATTERING_NN_VARIATIONAL

  CALL LOGGER%LOG_WARNING("================================")
  
  ENERGY(1) = E
  K2 = ENERGY(1)/HTM
  CALL NN_SCATTERING_VARIATIONAL_ENERGIES_CHANNELS(ENERGY, CHANNELS, LEMP, PS, IPOT=IPOT, ILB=ILB)
  CALL LOGGER%LOG_INFO("Energy: " // TRIM(TO_STRING(ENERGY(1))))
  CALL LOGGER%LOG_INFO("K: " // TRIM(TO_STRING(SQRT(K2))))
  CALL LOGGER%LOG_DEBUG("R11: " // TRIM(TO_STRING(PS(1,1)%R_BB(1,1)/SQRT(K2))))
  CALL LOGGER%LOG_DEBUG("R12: " // TRIM(TO_STRING(PS(1,1)%R_BB(2,1)/SQRT(K2))))
  CALL LOGGER%LOG_DEBUG("R22: " // TRIM(TO_STRING(PS(1,1)%R_BB(2,2)/SQRT(K2))))
  RBB2 = PS(1,1)%R_BB
  IF (CHANNELS(1)%IS_COUPLED()) THEN
    IF ( SQRT(K2) > K_SMALL) THEN
      BLOCK 
      DOUBLE PRECISION :: EPS, D1, D2
      ! CALL LOGGER%LOG_DEBUG("EPS: " // TRIM(TO_STRING(PS(1,1)%epsilon_BB)))
      D1  = PS(1,1)%delta1_BB  * PI / 180.0D0
      D2  = PS(1,1)%delta2_BB  * PI / 180.0D0
      EPS = PS(1,1)%epsilon_BB * PI / 180.0D0

      CALL LOGGER%LOG_DEBUG("D1: " // TRIM(TO_STRING(D1)))
      CALL LOGGER%LOG_DEBUG("D2: " // TRIM(TO_STRING(D2)))
      CALL LOGGER%LOG_DEBUG("EPS: " // TRIM(TO_STRING(EPS)))

      RBB2(1,1) =  DOUBLE_FACTORIAL(2*L+1)**2 * &
                   (TAN(D1) * COS(EPS)**2  / SQRT(K2)**(2*L+1) + TAN(D2) * SIN(EPS)**2  / SQRT(K2)**(2*L+1))
      RBB2(1,2) =  DOUBLE_FACTORIAL(2*L+1) * DOUBLE_FACTORIAL(2*L+5) * &
                   ((TAN(D1) - TAN(D2)) * COS(EPS) * SIN(EPS) / SQRT(K2)**(2*L+3))
      RBB2(2,1) =  RBB2(1,2)
      RBB2(2,2) =  DOUBLE_FACTORIAL(2*L+5)**2 * &
                   (TAN(D1) * SIN(EPS)**2  / SQRT(K2)**(2*L+5) + TAN(D2) * COS(EPS)**2  / SQRT(K2)**(2*L+5))
      END BLOCK
    ENDIF
  ELSE
    IF ( SQRT(K2) > K_SMALL) THEN
      RBB2(1,1) =   RBB2(1,1) * DOUBLE_FACTORIAL(2*L+1)**2 / SQRT(K2)**(2*L+1)
    ENDIF
  ENDIF
  CALL LOGGER%LOG_INFO("R11: " // TRIM(TO_STRING(RBB2(1,1))))
  CALL LOGGER%LOG_INFO("R12: " // TRIM(TO_STRING(RBB2(1,2))))
  CALL LOGGER%LOG_INFO("R22: " // TRIM(TO_STRING(RBB2(2,2))))

  R0 = 0.D0
  r0(1) = -2 * DOUBLE_FACTORIAL(2*L+1)**2 * (RBB2(1,1) - RBB1(1,1))/(K2 * RBB1(1,1)**2);
  IF (CHANNELS(1)%IS_COUPLED()) THEN
    r0(2) = -2 * DOUBLE_FACTORIAL(2*L+5)**2 * (RBB2(2,2) - RBB1(2,2))/(K2 * RBB1(2,2)**2);
  ENDIF
  write(*,*) E, SQRT(K2), r0, SQRT(K2) > K_SMALL


END PROGRAM MAIN_SCATTERING_ZERO_ENERGY_R0