PROGRAM MAIN_SCATTERING_ZERO_ENERGY_R0
  USE SCATTERING_NN_VARIATIONAL
  USE QUANTUM_NUMBERS
  USE SCATTERING
  USE LOG, ONLY: LOG_OBJ => LOGGER
  USE EFT_PLESS, ONLY: LECS_EFT_PLESS, GET_LECS
  USE strings_utils
  IMPLICIT NONE
  
  DOUBLE PRECISION, PARAMETER :: K_SMALL = 1.d-8
  DOUBLE PRECISION, PARAMETER :: PI = 4.D0*DATAN(1.D0)
  TYPE(LOG_OBJ) :: LOGGER
  CHARACTER(LEN=1024) :: MESSAGE
  INTEGER, PARAMETER :: LMAX = 0, JMAX = 0, TZ = 0
  INTEGER, PARAMETER :: LEMP = 0
  TYPE(SCATTERING_CHANNEL) :: CHANNELS(1)
  TYPE(PHASE_SHIFT_RESULT) :: PS(1,3)
  DOUBLE PRECISION :: ENERGY(1) = 0.0D0
  INTEGER :: NCHANNELS
  DOUBLE PRECISION RBB0(2,2), RBB(2,2), K2, HTM, r0(2), E
  INTEGER :: L, S, J, NEQ
  INTEGER, EXTERNAL :: DOUBLE_FACTORIAL
  TYPE(ZERO_ENERGY_OBSERVABLES) :: ZEOBS
  TYPE(LECS_EFT_PLESS) :: LECS

  ! Read E from first argument if provided
  IF (COMMAND_ARGUMENT_COUNT() >= 1) THEN
    CALL GET_COMMAND_ARGUMENT(1, MESSAGE)
    READ(MESSAGE, *) E
  ELSE
    STOP "No energy provided. Please provide an energy value as the first argument."
  END IF

  CALL LOGGER%SET_LOG_MAX_LEVEL(3)

  L = 1
  S = 1
  J = 1
  CALL SET_CHANNEL(CHANNELS(1), J, L, S, TZ)
  NEQ = CHANNELS(1)%NCH()
  ! CALL CHANNELS(1)%TO_STRING(MESSAGE)
  ! CALL LOGGER%LOG_DEBUG(TRIM(MESSAGE))

  CALL SET_DYNAMIC(.TRUE.)
  LECS = GET_LECS(10)
  LECS%RC(1,1) = 2.6D0
  CALL LECS%CONVERT_TO_ADIMENSIONAL(1,1)
  LECS%CNLO(4) = 4.D0
  LECS%CNLO(6) = 0.5D0
  LECS%CNLO(7) =-0.5D0
  CALL LECS%CONVERT_TO_DIMENSIONAL(1,1)


  CALL NN_SCATTERING_VARIATIONAL_ENERGIES_CHANNELS(ENERGY, CHANNELS, LEMP, PS, LECS_FOR_PLESS=LECS)
  ! CALL LOGGER%LOG_INFO("Energy: " // TRIM(TO_STRING(ENERGY(1))))
  ! CALL LOGGER%LOG_INFO("R11: " // TRIM(TO_STRING(PS(1,1)%R_BB(1,1))))
  ! CALL LOGGER%LOG_INFO("R12: " // TRIM(TO_STRING(PS(1,1)%R_BB(2,1))))
  ! CALL LOGGER%LOG_INFO("R22: " // TRIM(TO_STRING(PS(1,1)%R_BB(2,2))))
  RBB0 = PS(1,1)%R_BB
  ZEOBS = EVALUATE_ZERO_ENERGIES_OBSERVABLES_STAPP(RBB0, NEQ, L)
  ! CALL LOGGER%LOG_INFO("a0 : " // TRIM(TO_STRING(ZEOBS%a1)))
  IF (NEQ == 2) THEN
    ! CALL LOGGER%LOG_INFO("a1 : " // TRIM(TO_STRING(ZEOBS%a2)))
    ! CALL LOGGER%LOG_INFO("eJ : " // TRIM(TO_STRING(ZEOBS%e)))
  ENDIF
  HTM = GET_HTM()
  CALL RESET_SCATTERING_NN_VARIATIONAL

  ! CALL LOGGER%LOG_WARNING("================================")
  CALL SET_DYNAMIC(.TRUE.)
  
  ENERGY(1) = E
  K2 = ENERGY(1)/HTM
  CALL NN_SCATTERING_VARIATIONAL_ENERGIES_CHANNELS(ENERGY, CHANNELS, LEMP, PS, LECS_FOR_PLESS=LECS)
  ! CALL LOGGER%LOG_INFO("Energy: " // TRIM(TO_STRING(ENERGY(1))))
  ! CALL LOGGER%LOG_INFO("K: " // TRIM(TO_STRING(SQRT(K2))))
  ! CALL LOGGER%LOG_DEBUG("R11: " // TRIM(TO_STRING(PS(1,1)%R_BB(1,1))))
  ! CALL LOGGER%LOG_DEBUG("R12: " // TRIM(TO_STRING(PS(1,1)%R_BB(2,1))))
  ! CALL LOGGER%LOG_DEBUG("R22: " // TRIM(TO_STRING(PS(1,1)%R_BB(2,2))))
  RBB = PS(1,1)%R_BB
  IF (CHANNELS(1)%IS_COUPLED()) THEN
    IF ( SQRT(K2) > K_SMALL) THEN
      BLOCK 
      DOUBLE PRECISION :: EPS, D1, D2
      ! CALL LOGGER%LOG_DEBUG("EPS: " // TRIM(TO_STRING(PS(1,1)%epsilon_BB)))
      D1  = PS(1,1)%delta1_BB  * PI / 180.0D0
      D2  = PS(1,1)%delta2_BB  * PI / 180.0D0
      EPS = PS(1,1)%epsilon_BB * PI / 180.0D0

      ! CALL LOGGER%LOG_DEBUG("D1: " // TRIM(TO_STRING(D1)))
      ! CALL LOGGER%LOG_DEBUG("D2: " // TRIM(TO_STRING(D2)))
      ! CALL LOGGER%LOG_DEBUG("EPS: " // TRIM(TO_STRING(EPS)))

      RBB(1,1) =  DOUBLE_FACTORIAL(2*L+1)**2 * &
                   (TAN(D1) * COS(EPS)**2  / SQRT(K2)**(2*L+1) + TAN(D2) * SIN(EPS)**2  / SQRT(K2)**(2*L+1))
      RBB(1,2) =  DOUBLE_FACTORIAL(2*L+1) * DOUBLE_FACTORIAL(2*L+5) * &
                   ((TAN(D1) - TAN(D2)) * COS(EPS) * SIN(EPS) / SQRT(K2)**(2*L+3))
      RBB(2,1) =  RBB(1,2)
      RBB(2,2) =  DOUBLE_FACTORIAL(2*L+5)**2 * &
                   (TAN(D1) * SIN(EPS)**2  / SQRT(K2)**(2*L+5) + TAN(D2) * COS(EPS)**2  / SQRT(K2)**(2*L+5))
      END BLOCK
    ENDIF
  ELSE
    IF ( SQRT(K2) > K_SMALL) THEN
      ! CALL LOGGER%LOG_DEBUG("R11: " // TRIM(TO_STRING(RBB(1,1))))
      RBB(1,1) =   RBB(1,1) * DOUBLE_FACTORIAL(2*L+1)**2 / SQRT(K2)**(2*L+1)
    ENDIF
  ENDIF
  ! CALL LOGGER%LOG_INFO("R11: " // TRIM(TO_STRING(RBB(1,1))))
  ! CALL LOGGER%LOG_INFO("R12: " // TRIM(TO_STRING(RBB(1,2))))
  ! CALL LOGGER%LOG_INFO("R22: " // TRIM(TO_STRING(RBB(2,2))))

  R0 = 0.D0
  r0(1) = -2 * DOUBLE_FACTORIAL(2*L+1)**2 * (RBB(1,1) - RBB0(1,1))/(K2 * RBB0(1,1)**2);
  IF (CHANNELS(1)%IS_COUPLED()) THEN
    r0(2) = -2 * DOUBLE_FACTORIAL(2*L+5)**2 * (RBB(2,2) - RBB0(2,2))/(K2 * RBB0(2,2)**2);
  ENDIF
  WRITE(*,*) "RBB0: ", RBB0
  WRITE(*,*) "RBB: ", RBB
  WRITE(*,*) "RBB - RBB0: ", RBB - RBB0
  WRITE(*,*) "K**(2L+1): ", K2**(2*L+1)
  WRITE(*,*) "-2 * DOUBLE_FACTORIAL(2*L+1)**2 / RBB0(1,1)**2: ", -2 * DOUBLE_FACTORIAL(2*L+1)**2 / RBB0(1,1)**2
  WRITE(*,*) E, SQRT(K2), r0, SQRT(K2) > K_SMALL


END PROGRAM MAIN_SCATTERING_ZERO_ENERGY_R0