PROGRAM MAIN_SCATTERING_ZERO_ENERGY_R0
  USE SCATTERING_NN_VARIATIONAL
  USE QUANTUM_NUMBERS
  USE SCATTERING
  USE EFT_PLESS, ONLY: LECS_EFT_PLESS, GET_LECS
  IMPLICIT NONE

  ! Parameters for my case of interest
  INTEGER, PARAMETER :: LMAX = 0, JMAX = 0, TZ = 0
  INTEGER, PARAMETER :: LEMP = 0
  INTEGER, PARAMETER :: L = 1, S = 1
  
  ! Size parameters and some physical constants
  INTEGER, PARAMETER :: NE = 2, NCHANNELS = 3, RDIM = 2, FIT_ORDER = 2
  DOUBLE PRECISION, PARAMETER :: K_SMALL = 1.d-8
  DOUBLE PRECISION, PARAMETER :: PI = 4.D0*DATAN(1.D0)

  ! Variables for logging and messages
  CHARACTER(LEN=1024) :: MESSAGE

  ! Inputs and outputs for the scattering modules
  TYPE(SCATTERING_CHANNEL) :: CHANNELS(NCHANNELS)
  DOUBLE PRECISION :: ENERGIES(NE)
  TYPE(PHASE_SHIFT_RESULT) :: PS(NCHANNELS, NE)
  TYPE(ZERO_ENERGY_OBSERVABLES) :: ZEOBS
  TYPE(LECS_EFT_PLESS) :: LECS

  ! R_BB matrices
  DOUBLE PRECISION RBB0(RDIM,RDIM), RBB(RDIM,RDIM), K2, HTM, R0, A0, E

  INTEGER :: NEQ, ICH
  INTEGER, EXTERNAL :: DOUBLE_FACTORIAL

  ! Read E from first argument if provided
  IF (COMMAND_ARGUMENT_COUNT() >= 1) THEN
    CALL GET_COMMAND_ARGUMENT(1, MESSAGE)
    READ(MESSAGE, *) E
  ELSE
    STOP "No energy provided. Please provide an energy value as the first argument."
  END IF
  ENERGIES(1) = 0
  ENERGIES(2) = E

  CALL SET_MAX_LOG_LEVEL(0)

  CALL SET_CHANNEL(CHANNELS(1), 0, L, S, TZ)
  CALL SET_CHANNEL(CHANNELS(2), 1, L, S, TZ)
  CALL SET_CHANNEL(CHANNELS(3), 2, L, S, TZ)

  CALL SET_DYNAMIC(.TRUE.)
  LECS = GET_LECS(10)
  LECS%RC(1,1) = 2.6D0
  CALL LECS%CONVERT_TO_ADIMENSIONAL(1,1)
  LECS%CNLO(4) = 4.D0
  LECS%CNLO(6) = 0.5D0
  LECS%CNLO(7) =-0.5D0
  CALL LECS%CONVERT_TO_DIMENSIONAL(1,1)


  CALL NN_SCATTERING_VARIATIONAL_ENERGIES_CHANNELS(ENERGIES, CHANNELS, LEMP, PS, LECS_FOR_PLESS=LECS)
  HTM = GET_HTM()
  CALL RESET_SCATTERING_NN_VARIATIONAL

  K2 = ENERGIES(2)/HTM
  DO ICH = 1, NCHANNELS
    NEQ = CHANNELS(ICH)%NCH()

    ! Saving the R_BB matrix at zero energy and saving the scattering lengths
    RBB0 = PS(ICH,1)%R_BB
    ZEOBS = EVALUATE_ZERO_ENERGIES_OBSERVABLES_STAPP(RBB0, NEQ, L)
    A0 = ZEOBS%a1
    
    ! Evaluating r_e using the R_BB matrix at non-zero energy
    RBB = PS(ICH,2)%R_BB
    IF ( SQRT(K2) > K_SMALL) THEN       ! K < K_SMALL
      RBB(1,1) =   RBB(1,1) * DOUBLE_FACTORIAL(2*L+1)**2 / SQRT(K2)**(2*L+1)
    ENDIF                           ! End of if about coupled or uncoupled channels

    R0 = -2 * DOUBLE_FACTORIAL(2*L+1)**2 * (RBB(1,1) - RBB0(1,1))/(K2 * RBB0(1,1)**2);
    WRITE(*,*) LECS%RC(1,1), LECS%CNLO(4), LECS%CNLO(6), LECS%CNLO(7), A0, R0
  ENDDO


END PROGRAM MAIN_SCATTERING_ZERO_ENERGY_R0