MODULE PHYSICAL_CONSTANTS
  USE ANGLES
  IMPLICIT NONE

  DOUBLE PRECISION, PARAMETER :: HBARC = 197.327053D0  ! MeV fm
  DOUBLE PRECISION, PARAMETER :: MASS_PROTON = 938.272029D0  ! MeV
  DOUBLE PRECISION, PARAMETER :: MASS_NEUTRON = 939.565630D0  ! MeV
  DOUBLE PRECISION, PARAMETER :: MASS_NUCLEON = (MASS_PROTON + MASS_NEUTRON) / 2.D0  ! MeV
  DOUBLE PRECISION, PARAMETER :: MASS_REDUCED_NP = MASS_PROTON*MASS_NEUTRON/(MASS_PROTON+MASS_NEUTRON)  ! MeV
  DOUBLE PRECISION, PARAMETER :: MASS_DEUTERON = 1875.612D0  ! MeV
  DOUBLE PRECISION, PARAMETER :: MASS_TRITON = 2808.921D0  ! MeV
  DOUBLE PRECISION, PARAMETER :: MASS_HELIUM3 = 2809.415D0  ! MeV
  DOUBLE PRECISION, PARAMETER :: MASS_HELIUM4 = 3727.379D0  ! MeV
  DOUBLE PRECISION, PARAMETER :: MASS_PION = 139.57039D0  ! MeV

  DOUBLE PRECISION, PARAMETER :: HBARM_P = HBARC**2 / (2.0D0 * MASS_PROTON)  ! MeV fm^2
  DOUBLE PRECISION, PARAMETER :: HBARM_N = HBARC**2 / (2.0D0 * MASS_NEUTRON)  ! MeV fm^2
  DOUBLE PRECISION, PARAMETER :: HBARM_NP = HBARC**2 / (2.0D0 * MASS_REDUCED_NP)  ! MeV fm^2
  
  DOUBLE PRECISION, PARAMETER :: MASS_ELECTRON = 0.510998946D0  ! MeV
  DOUBLE PRECISION, PARAMETER :: MASS_MUON = 105.6583745D0  ! MeV
  DOUBLE PRECISION, PARAMETER :: MASS_TAU = 1776.86D0  ! MeV
  DOUBLE PRECISION, PARAMETER :: MASS_Z_BOSON = 9.11876D3  ! MeV
  DOUBLE PRECISION, PARAMETER :: MASS_W_BOSON = 8.0379D3  ! MeV
  DOUBLE PRECISION, PARAMETER :: MASS_HIGGS_BOSON = 125.1D3  ! MeV

  DOUBLE PRECISION, PARAMETER :: ALPHA_FINE_STRUCTURE = 1.0D0 / 137.035999084D0  ! Fine-structure constant
  DOUBLE PRECISION, PARAMETER :: ALPHA_HBARC = ALPHA_FINE_STRUCTURE * HBARC  ! Fine-structure constant in MeV fm

CONTAINS
  PURE FUNCTION REDUCED_MASS(M1, M2) RESULT(MU)
    IMPLICIT NONE
    DOUBLE PRECISION, INTENT(IN) :: M1, M2
    DOUBLE PRECISION :: MU

    MU = (M1 * M2) / (M1 + M2)
  END FUNCTION REDUCED_MASS

  PURE FUNCTION HBARM(MASS)
    IMPLICIT NONE
    DOUBLE PRECISION, INTENT(IN) :: MASS
    DOUBLE PRECISION :: HBARM

    HBARM = HBARC**2 / (2*MASS)  ! MeV fm^2
  END FUNCTION HBARM

  FUNCTION HBARM_NUCLEON_NUCLEON(TZ) RESULT(HBARM_NN)
    IMPLICIT NONE
    INTEGER, INTENT(IN) :: TZ
    DOUBLE PRECISION :: HBARM_NN

    IF (TZ == 0) THEN
      HBARM_NN = HBARM_NP  ! Neutron-proton reduced mass
    ELSE IF (TZ == 1) THEN
      HBARM_NN = HBARM_P  ! Proton-proton reduced mass
    ELSE IF (TZ == -1) THEN
      HBARM_NN = HBARM_N  ! Neutron-neutron reduced mass
    ELSE
      STOP "Invalid TZ value in HBARM_NUCLEON_NUCLEON"
    END IF
  END FUNCTION HBARM_NUCLEON_NUCLEON

  SUBROUTINE SET_REDUCED_MASS_AND_HTM(TZ, MASS, HTM)
    IMPLICIT NONE
    INTEGER, INTENT(IN) :: TZ  ! 0 for np, 1 for pp, -1 for nn
    DOUBLE PRECISION, INTENT(OUT) :: MASS  ! Mass of the particle in MeV
    DOUBLE PRECISION, INTENT(OUT) :: HTM  ! HTM value in MeV fm^2

    SELECT CASE (TZ)
      CASE (0)  ! Neutron-proton
        MASS = MASS_REDUCED_NP  ! Use reduced mass for np
        HTM = HBARM_NP
      CASE (1)  ! Proton-proton
        MASS = MASS_PROTON  ! Use proton mass for pp
        HTM = HBARM_P
      CASE (-1)  ! Neutron-neutron
        MASS = MASS_NEUTRON  ! Use neutron mass for nn
        HTM = HBARM_N
      CASE DEFAULT
        STOP "Invalid TZ value in SET_REDUCED_MASS_AND_HTM"
    END SELECT
  END SUBROUTINE SET_REDUCED_MASS_AND_HTM

END MODULE PHYSICAL_CONSTANTS