name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          for i in 1 2 3; do
            sudo apt-get update && sudo apt-get install -y gfortran libgsl-dev liblapack-dev && break
            sleep 10
          done

      - name: Build with Make
        run: make all